#!/usr/bin/env python3
"""
build_dart.py — Generates Dart icon constants from data/icons

Usage:  python3 tool/build_dart.py

Output:
  lib/src/icons.dart    Dart file with all icon SVG path data
"""

import os
import re


ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
ICONS_DIR = os.path.join(ROOT, 'data', 'icons')
OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'lib', 'src')
OUT_PATH = os.path.join(OUT_DIR, 'icons.dart')


def to_camel(kebab: str) -> str:
    parts = kebab.split('-')
    if not parts:
        return kebab
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])


def strip_svg(code: str) -> str:
    if not code:
        return ''
    code = re.sub(r'^<svg[^>]*>', '', code)
    code = re.sub(r'</svg>\s*$', '', code)
    return code.strip()


def normalize_svg_colors(code: str) -> str:
    return (
        code
        .replace('#1C274C', 'currentColor')
        .replace('#1c274c', 'currentColor')
        .replace('fill="white"', 'fill="currentColor"')
        .replace('stroke="white"', 'stroke="currentColor"')
    )


def read_weight(icon_dir: str, filename: str) -> str:
    path = os.path.join(icon_dir, filename)
    if not os.path.exists(path):
        return ''
    with open(path, 'r') as f:
        return strip_svg(normalize_svg_colors(f.read()))


def iter_icon_dirs():
    if not os.path.isdir(ICONS_DIR):
        raise FileNotFoundError(f'Icon source directory not found at {ICONS_DIR}')

    for category in sorted(os.listdir(ICONS_DIR)):
        category_dir = os.path.join(ICONS_DIR, category)
        if not os.path.isdir(category_dir):
            continue
        for icon_name in sorted(os.listdir(category_dir)):
            icon_dir = os.path.join(category_dir, icon_name)
            if os.path.isdir(icon_dir):
                yield category, icon_name, icon_dir


def generate():
    print(f'Reading {ICONS_DIR} ...')

    weight_files = [
        ('outline', 'outline.svg', 'Outline'),
        ('filled', 'filled.svg', 'Filled'),
        ('duotoneOutline', 'duotone-outline.svg', 'Duotone Outline'),
        ('duotoneFilled', 'duotone-filled.svg', 'Duotone Filled'),
    ]
    weight_maps = {accessor: {} for accessor, _filename, _label in weight_files}
    seen = set()

    for cat_key, icon_key, icon_dir in iter_icon_dirs():
        name = to_camel(icon_key)

        if name in seen:
            name = name + to_camel(cat_key).capitalize()
        seen.add(name)

        for accessor, filename, _label in weight_files:
            svg = read_weight(icon_dir, filename)
            if svg:
                weight_maps[accessor][name] = svg

    all_names = sorted(set().union(*(weight_map.keys() for weight_map in weight_maps.values())))
    print('  ' + '  '.join(f'{label}: {len(weight_maps[accessor])}' for accessor, _filename, label in weight_files))

    os.makedirs(OUT_DIR, exist_ok=True)

    lines = []
    lines.append('// Auto-generated by tool/build_dart.py — do not edit.')
    lines.append('')
    lines.append(f'// {len(all_names)} icons across generated weights.')
    lines.append('// ignore_for_file: non_constant_identifier_names')
    lines.append('')
    lines.append('/// Vezham icon library. Access icons by weight:')
    lines.append('/// ```dart')
    lines.append("/// Vezham.outline.home")
    lines.append("/// Vezham.filled.settings")
    lines.append("/// Vezham.duotoneOutline.star")
    lines.append("/// Vezham.duotoneFilled.heart")
    lines.append('/// ```')
    lines.append('class Vezham {')
    lines.append('  Vezham._();')
    lines.append('')
    for accessor, _filename, label in weight_files:
        lines.append(f'  /// {label} weight icons.')
        lines.append(f"  static final VezhamIconWeight {accessor} = VezhamIconWeight._(_{accessor}, '{label}');")
        lines.append('')
    lines.append('}')
    lines.append('')

    for accessor, _filename, _label in weight_files:
        lines.append(f'final Map<String, String> _{accessor} = {{')
        for name in sorted(weight_maps[accessor].keys()):
            lines.append(f"  '{name}': r'''{weight_maps[accessor][name]}''',")
        lines.append('};')
        lines.append('')

    lines.append('/// A weight variant of Vezham icons.')
    lines.append('class VezhamIconWeight {')
    lines.append('  final Map<String, String> _icons;')
    lines.append('  final String _name;')
    lines.append('  const VezhamIconWeight._(this._icons, this._name);')
    lines.append('')
    lines.append('  /// Display name of this weight.')
    lines.append("  String get name => _name;")
    lines.append('')
    lines.append('  /// Number of icons in this weight.')
    lines.append("  int get length => _icons.length;")
    lines.append('')
    lines.append('  /// All icon names in this weight.')
    lines.append("  Iterable<String> get names => _icons.keys;")
    lines.append('')
    lines.append('  /// Looks up SVG path data by [iconName], or null if not found.')
    lines.append("  String? operator [](String iconName) => _icons[iconName];")
    lines.append('')
    for n in all_names:
        lines.append(f'  /// SVG path data for the "{n}" icon.')
        lines.append(f"  String get {n} => _icons['{n}'] ?? '';")
    lines.append('')
    lines.append('  @override')
    lines.append("  String toString() => 'VezhamIconWeight.$_name(${_icons.length} icons)';")
    lines.append('}')
    lines.append('')

    content = '\n'.join(lines)
    with open(OUT_PATH, 'w') as f:
        f.write(content)

    print(f'\nGenerated {OUT_PATH}')
    print('  ' + ' / '.join(f'{len(weight_maps[accessor])} {accessor}' for accessor, _filename, _label in weight_files))


if __name__ == '__main__':
    generate()
