#!/usr/bin/env python3
"""
build_dart.py — Generates Dart icon constants from data/icon-data.json

Usage:  python3 tool/build_dart.py

Output:
  lib/src/icons.dart    Dart file with all icon SVG path data
"""

import json
import os
import re


ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
DATA_PATH = os.path.join(ROOT, 'data', 'icon-data.json')
OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'lib', 'src')
OUT_PATH = os.path.join(OUT_DIR, 'icons.dart')


def to_camel(kebab: str) -> str:
    parts = kebab.split('-')
    if not parts:
        return kebab
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])


def strip_svg(code: str) -> str:
    if not code:
        return ''
    code = re.sub(r'^<svg[^>]*>', '', code)
    code = re.sub(r'</svg>\s*$', '', code)
    return code.strip()


def generate():
    print(f'Reading {DATA_PATH} ...')
    with open(DATA_PATH, 'r') as f:
        data = json.load(f)

    categories = data.get('categories', {})

    outline_map = {}
    filled_map = {}
    seen = set()

    for cat_key, cat_data in categories.items():
        for icon_key, icon in cat_data.get('icons', {}).items():
            weights = icon.get('weights', {})
            name = to_camel(icon_key)

            if name in seen:
                name = name + to_camel(cat_key).capitalize()
            seen.add(name)

            ow = weights.get('Outline', {})
            osvg = strip_svg(ow.get('code', ''))
            if osvg:
                outline_map[name] = osvg

            fw = weights.get('Filled', {})
            fsvg = strip_svg(fw.get('code', ''))
            if fsvg:
                filled_map[name] = fsvg

    all_names = sorted(outline_map.keys())
    print(f'  Outline: {len(outline_map)}  Filled: {len(filled_map)}')

    os.makedirs(OUT_DIR, exist_ok=True)

    lines = []
    lines.append('// Auto-generated by tool/build_dart.py — do not edit.')
    lines.append('')
    lines.append(f'// {len(all_names)} icons per weight.')
    lines.append('// ignore_for_file: non_constant_identifier_names')
    lines.append('')
    lines.append('/// Reicon icon library. Access icons by weight:')
    lines.append('/// ```dart')
    lines.append("/// Reicon.outline.home")
    lines.append("/// Reicon.filled.settings")
    lines.append('/// ```')
    lines.append('class Reicon {')
    lines.append('  Reicon._();')
    lines.append('')
    lines.append('  /// Outline weight icons.')
    lines.append('  static final ReiconWeight outline = ReiconWeight._(_outline, \'Outline\');')
    lines.append('')
    lines.append('  /// Filled weight icons.')
    lines.append('  static final ReiconWeight filled = ReiconWeight._(_filled, \'Filled\');')
    lines.append('}')
    lines.append('')

    lines.append('final Map<String, String> _outline = {')
    for name in all_names:
        lines.append(f"  '{name}': r'''{outline_map[name]}''',")
    lines.append('};')
    lines.append('')

    lines.append('final Map<String, String> _filled = {')
    for name in all_names:
        lines.append(f"  '{name}': r'''{filled_map[name]}''',")
    lines.append('};')
    lines.append('')

    lines.append('/// A weight variant of Reicon icons ([Reicon.outline], [Reicon.filled]).')
    lines.append('class ReiconWeight {')
    lines.append('  final Map<String, String> _icons;')
    lines.append('  final String _name;')
    lines.append('  const ReiconWeight._(this._icons, this._name);')
    lines.append('')
    lines.append('  /// Display name of this weight.')
    lines.append("  String get name => _name;")
    lines.append('')
    lines.append('  /// Number of icons in this weight.')
    lines.append("  int get length => _icons.length;")
    lines.append('')
    lines.append('  /// All icon names in this weight.')
    lines.append("  Iterable<String> get names => _icons.keys;")
    lines.append('')
    lines.append('  /// Looks up SVG path data by [iconName], or null if not found.')
    lines.append("  String? operator [](String iconName) => _icons[iconName];")
    lines.append('')
    for n in all_names:
        lines.append(f'  /// SVG path data for the "{n}" icon.')
        lines.append(f"  String get {n} => _icons['{n}']!;")
    lines.append('')
    lines.append('  @override')
    lines.append("  String toString() => 'ReiconWeight.$_name(${_icons.length} icons)';")
    lines.append('}')
    lines.append('')

    content = '\n'.join(lines)
    with open(OUT_PATH, 'w') as f:
        f.write(content)

    print(f'\nGenerated {OUT_PATH}')
    print(f'  {len(outline_map)} outline / {len(filled_map)} filled')


if __name__ == '__main__':
    generate()
