import type { IconEntry, IconIndex, IconWeight, SearchResult } from './types.js';

// Only flag clearly conversational strings — short "add home icon" should be fine
const SENTENCE_MARKERS = /\?|!|\.{2,}/;
const SENTENCE_WORDS = /\b(please|could|would|want|need|show|find|give|get me|looking for|i am|i'm|can you|help me|what is)\b/i;

const SYNONYMS: Record<string, string[]> = {
  x: ['x', 'close', 'dismiss', 'cancel', 'remove'],
  trash: ['trash', 'delete', 'remove', 'bin', 'clear', 'erase', 'rubbish', 'garbage'],
  delete: ['delete', 'trash', 'remove', 'bin', 'clear', 'erase'],
  remove: ['remove', 'trash', 'delete', 'x', 'close', 'clear'],
  bin: ['bin', 'trash', 'delete', 'remove'],
  settings: ['settings', 'gear', 'cog', 'preferences', 'configure', 'options', 'setup'],
  gear: ['gear', 'settings', 'cog'],
  cog: ['cog', 'settings', 'gear'],
  preferences: ['preferences', 'settings', 'options'],
  search: ['search', 'magnifier', 'find', 'lookup', 'explore', 'magnify', 'scan'],
  magnifier: ['magnifier', 'search', 'find', 'magnify'],
  find: ['find', 'search', 'magnifier', 'lookup'],
  user: ['user', 'person', 'profile', 'account', 'avatar', 'member', 'human'],
  person: ['person', 'user', 'profile', 'human', 'individual'],
  profile: ['profile', 'user', 'person', 'account', 'avatar'],
  account: ['account', 'user', 'profile'],
  avatar: ['avatar', 'user', 'person', 'profile'],
  heart: ['heart', 'love', 'favorite', 'like'],
  love: ['love', 'heart', 'favorite'],
  favorite: ['favorite', 'heart', 'star', 'like'],
  like: ['like', 'heart', 'favorite', 'thumbs'],
  star: ['star', 'rating', 'favorite', 'bookmark', 'favourite'],
  rating: ['rating', 'star', 'stars'],
  home: ['home', 'house', 'main'],
  house: ['house', 'home'],
  menu: ['menu', 'hamburger', 'navigation', 'nav', 'drawer', 'bars'],
  hamburger: ['hamburger', 'menu', 'bars', 'nav'],
  navigation: ['navigation', 'menu', 'nav', 'drawer', 'hamburger'],
  close: ['close', 'x', 'dismiss', 'cancel', 'remove', 'exit'],
  dismiss: ['dismiss', 'close', 'x', 'cancel'],
  cancel: ['cancel', 'close', 'x', 'dismiss', 'stop'],
  exit: ['exit', 'close', 'x', 'leave', 'quit'],
  bell: ['bell', 'notification', 'alert', 'ring', 'alarm', 'notify'],
  notification: ['notification', 'bell', 'alert', 'notify', 'notif'],
  alert: ['alert', 'bell', 'notification', 'warning', 'danger'],
  ring: ['ring', 'bell', 'notification'],
  cart: ['cart', 'shopping', 'bag', 'basket', 'buy', 'purchase', 'shop'],
  shopping: ['shopping', 'cart', 'bag', 'basket', 'buy'],
  'shopping cart': ['shopping-cart', 'cart', 'cart-large'],
  bag: ['bag', 'cart', 'shopping', 'basket', 'purse', 'sack'],
  basket: ['basket', 'cart', 'shopping', 'bag'],
  phone: ['phone', 'call', 'contact', 'dial', 'telephone', 'mobile', 'smartphone'],
  call: ['call', 'phone', 'contact', 'dial'],
  mobile: ['mobile', 'phone', 'smartphone', 'cell'],
  mail: ['mail', 'email', 'envelope', 'letter', 'message', 'inbox', 'send'],
  email: ['email', 'mail', 'envelope', 'letter', 'message', 'inbox'],
  envelope: ['envelope', 'mail', 'email', 'letter'],
  letter: ['letter', 'mail', 'email', 'envelope'],
  message: ['message', 'chat', 'msg', 'text', 'talk', 'bubble', 'comment', 'conversation'],
  chat: ['chat', 'message', 'bubble', 'talk', 'comment', 'conversation', 'round'],
  msg: ['msg', 'message', 'chat', 'text'],
  comment: ['comment', 'message', 'chat', 'bubble'],
  inbox: ['inbox', 'mail', 'email', 'message'],
  send: ['send', 'share', 'submit', 'forward', 'export', 'transmit'],
  share: ['share', 'send', 'forward', 'export'],
  reply: ['reply', 'respond', 'answer', 'back'],
  clock: ['clock', 'time', 'hour', 'watch', 'stopwatch', 'timer'],
  time: ['time', 'clock', 'hour', 'watch', 'stopwatch'],
  watch: ['watch', 'clock', 'time', 'stopwatch'],
  stopwatch: ['stopwatch', 'timer', 'clock', 'watch'],
  timer: ['timer', 'stopwatch', 'clock', 'countdown'],
  calendar: ['calendar', 'date', 'day', 'schedule', 'month', 'event', 'agenda'],
  date: ['date', 'calendar', 'day', 'schedule', 'event'],
  schedule: ['schedule', 'calendar', 'date', 'event', 'agenda'],
  alarm: ['alarm', 'alarm-clock', 'clock', 'timer', 'ring', 'wake'],
  play: ['play', 'start', 'begin', 'video', 'movie', 'music'],
  start: ['start', 'play', 'begin'],
  pause: ['pause', 'break', 'interrupt', 'hold'],
  stop: ['stop', 'halt', 'end', 'finish', 'block'],
  volume: ['volume', 'sound', 'speaker', 'audio', 'music'],
  sound: ['sound', 'volume', 'speaker', 'audio'],
  speaker: ['speaker', 'volume', 'sound', 'audio'],
  audio: ['audio', 'sound', 'volume', 'speaker', 'music'],
  mute: ['mute', 'silent', 'quiet', 'no-sound', 'volume-off'],
  music: ['music', 'note', 'song', 'tune', 'melody', 'audio'],
  song: ['song', 'music', 'note', 'tune'],
  camera: ['camera', 'photo', 'picture', 'photograph', 'image', 'selfie'],
  photo: ['photo', 'camera', 'picture', 'image', 'photograph'],
  picture: ['picture', 'photo', 'image', 'camera', 'photograph'],
  gallery: ['gallery', 'image', 'photo', 'picture', 'album'],
  video: ['video', 'film', 'movie', 'camera', 'record'],
  film: ['film', 'video', 'movie'],
  microphone: ['microphone', 'mic', 'voice', 'record', 'audio', 'podcast'],
  mic: ['mic', 'microphone', 'voice', 'record'],
  edit: ['edit', 'pencil', 'pen', 'modify', 'update', 'change', 'write', 'draw'],
  pencil: ['pencil', 'edit', 'pen', 'write', 'draw'],
  pen: ['pen', 'edit', 'pencil', 'write', 'draw'],
  update: ['update', 'edit', 'modify', 'change', 'refresh', 'renew'],
  write: ['write', 'pen', 'pencil', 'edit', 'draw'],
  draw: ['draw', 'pen', 'pencil', 'brush', 'paint'],
  circle: ['circle', 'round', 'circular', 'dot', 'disc', 'ring'],
  round: ['round', 'circle', 'circular'],
  square: ['square', 'box', 'rectangle', 'block', 'quad'],
  rectangle: ['rectangle', 'square', 'box'],
  triangle: ['triangle', 'triangular', 'pyramid'],
  arrow: ['arrow', 'direction', 'pointer', 'chevron', 'angle', 'caret'],
  direction: ['direction', 'arrow', 'pointer', 'way', 'route'],
  pointer: ['pointer', 'arrow', 'cursor', 'hand'],
  chevron: ['chevron', 'arrow', 'angle', 'caret'],
  angle: ['angle', 'chevron', 'arrow', 'corner'],
  caret: ['caret', 'chevron', 'arrow', 'dropdown'],
  up: ['up', 'above', 'upward', 'raise', 'top', 'chevron-up', 'arrow-up'],
  down: ['down', 'below', 'downward', 'lower', 'bottom', 'chevron-down', 'arrow-down'],
  left: ['left', 'back', 'previous', 'before', 'chevron-left', 'arrow-left', 'west'],
  right: ['right', 'next', 'forward', 'after', 'chevron-right', 'arrow-right', 'east'],
  back: ['back', 'left', 'previous', 'return', 'undo', 'reverse', 'chevron-left'],
  next: ['next', 'right', 'forward', 'continue', 'chevron-right'],
  previous: ['previous', 'back', 'left', 'before', 'chevron-left'],
  'arrow-up': ['arrow-up', 'up', 'upward', 'above', 'top', 'chevron-up'],
  'arrow-down': ['arrow-down', 'down', 'downward', 'below', 'bottom', 'chevron-down'],
  'arrow-left': ['arrow-left', 'left', 'back', 'previous', 'chevron-left'],
  'arrow-right': ['arrow-right', 'right', 'next', 'forward', 'chevron-right'],
  add: ['add', 'plus', 'new', 'create', 'additional', 'increase', 'append'],
  plus: ['plus', 'add', 'new', 'create', 'additional'],
  new: ['new', 'add', 'plus', 'create'],
  create: ['create', 'add', 'new', 'plus', 'make'],
  minus: ['minus', 'subtract', 'remove', 'decrease', 'reduce', 'less'],
  subtract: ['subtract', 'minus', 'remove', 'decrease', 'reduce'],
  increase: ['increase', 'add', 'plus', 'up', 'grow', 'raise'],
  decrease: ['decrease', 'minus', 'subtract', 'down', 'reduce', 'lower'],
  lock: ['lock', 'secure', 'protect', 'safety', 'password', 'privacy', 'locked'],
  secure: ['secure', 'lock', 'protect', 'shield', 'safe', 'safety'],
  unlock: ['unlock', 'unlocked', 'open', 'lock-opened'],
  'lock-opened': ['lock-opened', 'unlock', 'unlocked', 'open'],
  save: ['save', 'download', 'store', 'keep', 'floppy', 'disk'],
  download: ['download', 'save', 'install', 'downloading', 'get', 'receive'],
  upload: ['upload', 'import', 'uploading', 'send', 'submit'],
  export: ['export', 'share', 'send', 'upload', 'extract'],
  import: ['import', 'upload', 'bring', 'load'],
  print: ['print', 'printer', 'printing', 'paper'],
  refresh: ['refresh', 'reload', 'restart', 'sync', 'update', 'renew', 'reset'],
  reload: ['reload', 'refresh', 'restart', 'reset'],
  restart: ['restart', 'refresh', 'reload', 'reset', 'reboot'],
  sync: ['sync', 'refresh', 'reload', 'synchronize', 'update'],
  filter: ['filter', 'refine', 'sort', 'narrow'],
  sort: ['sort', 'order', 'arrange', 'organize', 'filter'],
  copy: ['copy', 'duplicate', 'clone', 'clipboard', 'replicate'],
  paste: ['paste', 'clipboard', 'insert'],
  clipboard: ['clipboard', 'copy', 'paste'],
  cut: ['cut', 'scissors', 'trim', 'clip'],
  link: ['link', 'url', 'chain', 'hyperlink', 'connect', 'attach'],
  unlink: ['unlink', 'link-off', 'break', 'detach'],
  attach: ['attach', 'link', 'clip', 'paperclip'],
  paperclip: ['paperclip', 'clip', 'attach', 'link'],
  tag: ['tag', 'label', 'price', 'badge'],
  label: ['label', 'tag', 'badge', 'sticker'],
  pin: ['pin', 'map-point', 'marker', 'location', 'place', 'thumbtack', 'tack'],
  'map-point': ['map-point', 'pin', 'marker', 'location', 'place', 'address'],
  folder: ['folder', 'directory', 'file-manager', 'dir', 'bundle'],
  directory: ['directory', 'folder'],
  file: ['file', 'document', 'paper', 'page', 'doc', 'text'],
  document: ['document', 'file', 'paper', 'page', 'doc'],
  image: ['image', 'photo', 'picture', 'gallery', 'photograph', 'pic'],
  pdf: ['pdf', 'document', 'file', 'adobe'],
  map: ['map', 'location', 'place', 'navigation', 'direction', 'route', 'travel'],
  location: ['location', 'map', 'pin', 'place', 'address', 'position', 'map-point'],
  place: ['place', 'location', 'pin', 'map-point', 'address'],
  address: ['address', 'location', 'pin', 'map', 'map-point', 'home'],
  globe: ['globe', 'world', 'earth', 'planet', 'international', 'global'],
  world: ['world', 'globe', 'earth', 'planet', 'global'],
  planet: ['planet', 'globe', 'world', 'earth', 'space'],
  compass: ['compass', 'direction', 'navigate', 'navigation', 'guide'],
  route: ['route', 'direction', 'path', 'way', 'map', 'navigation'],
  road: ['road', 'route', 'street', 'map', 'direction', 'path', 'way'],
  shield: ['shield', 'security', 'safe', 'protect', 'guard', 'defense', 'armor'],
  security: ['security', 'shield', 'safe', 'protect', 'guard', 'lock'],
  safe: ['safe', 'shield', 'security', 'protect', 'vault'],
  key: ['key', 'password', 'access', 'credential', 'security', 'keyhole'],
  password: ['password', 'key', 'security', 'lock', 'access'],
  verified: ['verified', 'verify', 'check', 'confirm', 'badge', 'authentic'],
  verify: ['verify', 'verified', 'check', 'confirm', 'badge'],
  wifi: ['wifi', 'internet', 'network', 'connection', 'wireless', 'signal'],
  internet: ['internet', 'wifi', 'network', 'web', 'online', 'globe', 'browser'],
  network: ['network', 'wifi', 'internet', 'connection', 'connect'],
  connection: ['connection', 'connect', 'wifi', 'network', 'signal', 'linked'],
  signal: ['signal', 'wifi', 'network', 'connection', 'cellular', 'bars'],
  bluetooth: ['bluetooth', 'wireless', 'connect', 'pairing'],
  battery: ['battery', 'power', 'charge', 'energy', 'level'],
  power: ['power', 'on', 'off', 'switch', 'button', 'energy', 'battery'],
  energy: ['energy', 'power', 'battery', 'charge', 'lightning', 'bolt'],
  bolt: ['bolt', 'lightning', 'flash', 'energy', 'power', 'electric', 'speed'],
  lightning: ['lightning', 'bolt', 'flash', 'energy', 'electric', 'power', 'zap'],
  sun: ['sun', 'light', 'brightness', 'day', 'sunny', 'sunlight', 'weather', 'warm'],
  sunny: ['sunny', 'sun', 'bright', 'light', 'weather', 'clear'],
  moon: ['moon', 'night', 'dark', 'sleep', 'midnight', 'lunar'],
  night: ['night', 'moon', 'dark', 'sleep', 'evening'],
  cloud: ['cloud', 'weather', 'sky', 'cloudy', 'overcast'],
  clouds: ['clouds', 'cloud', 'weather', 'cloudy'],
  rain: ['rain', 'rainy', 'water', 'drop', 'weather', 'storm', 'precipitation'],
  drop: ['drop', 'water', 'rain', 'liquid', 'droplet', 'drip'],
  snow: ['snow', 'snowflake', 'winter', 'cold', 'ice', 'weather', 'freeze'],
  snowflake: ['snowflake', 'snow', 'winter', 'ice', 'cold'],
  storm: ['storm', 'thunder', 'lightning', 'rain', 'weather', 'tornado'],
  wind: ['wind', 'breeze', 'air', 'weather', 'blow'],
  temperature: ['temperature', 'thermometer', 'weather', 'hot', 'cold', 'heat'],
  thermometer: ['thermometer', 'temperature', 'hot', 'cold', 'weather', 'temp'],
  fire: ['fire', 'flame', 'hot', 'burn', 'heat', 'danger'],
  flame: ['flame', 'fire', 'hot', 'burn'],
  water: ['water', 'drop', 'droplet', 'rain', 'liquid', 'ocean', 'sea', 'wave'],
  wave: ['wave', 'water', 'ocean', 'sea', 'sound'],
  leaf: ['leaf', 'nature', 'plant', 'green', 'eco', 'environment', 'tree'],
  toggle: ['toggle', 'switch', 'on', 'off', 'enable', 'disable'],
  switch: ['switch', 'toggle', 'on', 'off', 'enable'],
  checkbox: ['checkbox', 'check', 'tick', 'select', 'option'],
  radio: ['radio', 'button', 'select', 'option', 'choice'],
  dropdown: ['dropdown', 'select', 'menu', 'caret', 'chevron-down'],
  database: ['database', 'db', 'data', 'storage', 'server', 'backup'],
  data: ['data', 'database', 'information', 'db', 'storage'],
  server: ['server', 'host', 'cloud', 'database', 'network'],
  'cloud upload': ['cloud-upload', 'upload', 'cloud', 'sync'],
  'cloud download': ['cloud-download', 'download', 'cloud', 'sync'],
  storage: ['storage', 'database', 'data', 'server', 'drive', 'disk'],
  drive: ['drive', 'storage', 'disk', 'hard-drive', 'hard'],
  code: ['code', 'coding', 'programming', 'developer', 'dev', 'script', 'brackets'],
  terminal: ['terminal', 'console', 'command', 'cli', 'shell', 'prompt', 'cmd'],
  command: ['command', 'terminal', 'console', 'key', 'cmd'],
  git: ['git', 'commit', 'branch', 'merge', 'repository', 'repo', 'version-control', 'github'],
  branch: ['branch', 'git', 'fork', 'tree', 'merge'],
  window: ['window', 'app', 'application', 'screen', 'display', 'ui', 'browser'],
  loading: ['loading', 'loader', 'spinner', 'loading-circle', 'progress', 'wait'],
  progress: ['progress', 'loading', 'loader', 'bar', 'spinner', 'percentage'],
  spinner: ['spinner', 'loading', 'loader', 'circle', 'progress', 'wait'],
  info: ['info', 'information', 'help', 'about', 'details', 'i'],
  'info-circle': ['info-circle', 'info', 'information', 'help'],
  help: ['help', 'info', 'information', 'question', 'support', 'faq', 'guide'],
  question: ['question', 'help', 'info', 'support', 'faq', 'quiz'],
  warning: ['warning', 'caution', 'danger', 'alert', 'error', 'exclamation'],
  danger: ['danger', 'warning', 'alert', 'error', 'caution', 'problem'],
  error: ['error', 'warning', 'alert', 'danger', 'problem', 'fail', 'issue', 'exclamation'],
  success: ['success', 'check', 'tick', 'done', 'complete', 'pass', 'approved', 'verified'],
  check: ['check', 'tick', 'success', 'done', 'complete', 'confirm', 'yes', 'approve'],
  tick: ['tick', 'check', 'success', 'done', 'complete', 'confirm'],
  done: ['done', 'check', 'tick', 'complete', 'success', 'finish'],
  complete: ['complete', 'done', 'check', 'tick', 'success', 'finish'],
  confirm: ['confirm', 'check', 'tick', 'verify', 'validate', 'approve'],
  dashboard: ['dashboard', 'home', 'overview', 'panel', 'admin', 'main', 'screen'],
  overview: ['overview', 'dashboard', 'summary', 'home'],
  admin: ['admin', 'settings', 'dashboard', 'control', 'manage', 'super'],
  chart: ['chart', 'graph', 'pie', 'bar', 'statistics', 'stats', 'data'],
  graph: ['graph', 'chart', 'pie', 'bar', 'statistics', 'stats', 'data'],
  stats: ['stats', 'statistics', 'chart', 'graph', 'data', 'analytics'],
  analytics: ['analytics', 'chart', 'graph', 'stats', 'data', 'insight'],
  brush: ['brush', 'paint', 'draw', 'art', 'design', 'paintbrush'],
  paint: ['paint', 'brush', 'color', 'art', 'draw', 'paintbrush', 'palette'],
  palette: ['palette', 'color', 'paint', 'art', 'design'],
  color: ['color', 'colour', 'paint', 'palette', 'art', 'hue'],
  design: ['design', 'art', 'paint', 'brush', 'palette', 'creative', 'tool'],
  tool: ['tool', 'tools', 'wrench', 'screwdriver', 'settings', 'configure'],
  car: ['car', 'vehicle', 'auto', 'automobile', 'drive', 'transport', 'sedan'],
  truck: ['truck', 'van', 'vehicle', 'delivery', 'pickup', 'lorry'],
  bus: ['bus', 'vehicle', 'transport', 'public'],
  bike: ['bike', 'bicycle', 'cycle', 'cycling', 'riding', 'cyclist'],
  bicycle: ['bicycle', 'bike', 'cycle', 'cycling'],
  airplane: ['airplane', 'plane', 'flight', 'fly', 'air', 'travel', 'airport', 'jet', 'aircraft'],
  plane: ['plane', 'airplane', 'flight', 'air', 'travel', 'jet'],
  train: ['train', 'railway', 'rail', 'subway', 'metro', 'tram'],
  ship: ['ship', 'boat', 'vessel', 'sea', 'ocean', 'sail', 'marine'],
  boat: ['boat', 'ship', 'sail', 'vessel', 'sea'],
  chair: ['chair', 'seat', 'sitting', 'furniture', 'armchair', 'office'],
  sofa: ['sofa', 'couch', 'seat', 'furniture', 'living-room', 'armchair'],
  bed: ['bed', 'sleep', 'rest', 'bedroom', 'furniture', 'mattress'],
  lamp: ['lamp', 'light', 'lighting', 'bulb', 'desk', 'illuminate'],
  'light bulb': ['lightbulb', 'bulb', 'lamp', 'light', 'idea'],
  bulb: ['bulb', 'light', 'lamp', 'idea', 'lightbulb'],
  table: ['table', 'desk', 'furniture', 'counter', 'surface'],
  cabinet: ['cabinet', 'closet', 'storage', 'furniture', 'wardrobe', 'cupboard'],
  kitchen: ['kitchen', 'cook', 'food', 'appliance', 'stove', 'oven', 'fridge'],
  food: ['food', 'meal', 'eat', 'dining', 'cuisine', 'restaurant', 'dish'],
  drink: ['drink', 'beverage', 'cup', 'glass', 'mug', 'water', 'coffee', 'tea'],
  coffee: ['coffee', 'drink', 'cafe', 'cup', 'mug', 'beverage'],
  tea: ['tea', 'drink', 'cup', 'beverage', 'hot'],
  cup: ['cup', 'drink', 'mug', 'coffee', 'tea', 'glass', 'water'],
  glass: ['glass', 'cup', 'drink', 'wine', 'water', 'wineglass'],
  bottle: ['bottle', 'drink', 'water', 'liquid', 'container'],
  pizza: ['pizza', 'food', 'meal', 'slice'],
  cake: ['cake', 'food', 'dessert', 'birthday', 'celebrate', 'bake'],
  gift: ['gift', 'present', 'box', 'package', 'wrap', 'birthday', 'holiday'],
  present: ['present', 'gift', 'box', 'package', 'wrap'],
  wallet: ['wallet', 'money', 'payment', 'pay', 'cash', 'purse', 'finance'],
  money: ['money', 'wallet', 'payment', 'cash', 'dollar', 'currency', 'finance', 'coin'],
  coin: ['coin', 'money', 'payment', 'cash', 'currency', 'finance'],
  dollar: ['dollar', 'money', 'cash', 'currency', 'finance', 'payment'],
  payment: ['payment', 'money', 'wallet', 'card', 'cash', 'checkout', 'pay'],
  health: ['health', 'medical', 'hospital', 'doctor', 'medicine', 'healthcare'],
  medical: ['medical', 'health', 'hospital', 'doctor', 'medicine'],
  hospital: ['hospital', 'medical', 'health', 'doctor', 'clinic'],
  pill: ['pill', 'medicine', 'tablet', 'drug', 'health', 'pharmacy', 'medication'],
  syringe: ['syringe', 'injection', 'vaccine', 'medical', 'health', 'needle'],
  pulse: ['pulse', 'heart', 'beat', 'cardio', 'vitals', 'health'],
  group: ['group', 'team', 'users', 'people', 'community', 'crowd', 'organization'],
  team: ['team', 'group', 'users', 'people', 'community'],
  users: ['users', 'people', 'group', 'team', 'community', 'crowd'],
  people: ['people', 'users', 'group', 'team', 'community', 'crowd', 'person'],
  community: ['community', 'group', 'team', 'users', 'people'],
  flag: ['flag', 'report', 'mark', 'indicator', 'country', 'nation', 'banner'],
  badge: ['badge', 'verified', 'certificate', 'award', 'achievement', 'medal'],
  sport: ['sport', 'fitness', 'exercise', 'athletic', 'game', 'activity'],
  fitness: ['fitness', 'sport', 'exercise', 'workout', 'gym', 'health'],
  gym: ['gym', 'fitness', 'exercise', 'workout', 'health', 'strong'],
  run: ['run', 'running', 'sprint', 'jog', 'exercise', 'fitness', 'race'],
  walk: ['walk', 'walking', 'hike', 'hiking', 'stroll', 'exercise', 'fitness'],
  dumbbell: ['dumbbell', 'weight', 'gym', 'fitness', 'exercise', 'muscle', 'workout'],
  gamepad: ['gamepad', 'controller', 'gaming', 'play', 'game', 'joystick'],
  gaming: ['gaming', 'game', 'gamepad', 'controller', 'console', 'play'],
  robot: ['robot', 'ai', 'automation', 'android', 'smart', 'tech'],
  rocket: ['rocket', 'launch', 'space', 'ship', 'startup', 'speed', 'fast', 'boost'],
  award: ['award', 'trophy', 'medal', 'prize', 'winner', 'achievement', 'badge', 'reward'],
  trophy: ['trophy', 'award', 'prize', 'winner', 'achievement', 'champion', 'cup'],
  medal: ['medal', 'award', 'trophy', 'prize', 'winner', 'achievement', 'badge', 'ribbon'],
  crown: ['crown', 'king', 'queen', 'royal', 'leader', 'top', 'best'],
  magic: ['magic', 'wand', 'sparkle', 'star', 'fantasy', 'creative', 'wizard'],
  fullscreen: ['fullscreen', 'full-screen', 'maximize', 'expand', 'enlarge', 'zoom'],
  maximize: ['maximize', 'fullscreen', 'expand', 'enlarge'],
  minimize: ['minimize', 'collapse', 'reduce', 'shrink', 'contract'],
  expand: ['expand', 'fullscreen', 'maximize', 'enlarge'],
  grid: ['grid', 'widget', 'layout', 'blocks', 'squares', 'tiles', 'dashboard'],
  list: ['list', 'bullets', 'items', 'listing', 'menu', 'options'],
  school: ['school', 'education', 'learn', 'study', 'academic', 'class', 'course'],
  education: ['education', 'school', 'learn', 'study', 'academic', 'knowledge'],
  book: ['book', 'read', 'reading', 'library', 'knowledge', 'education', 'learn', 'study'],
  library: ['library', 'book', 'books', 'read', 'education', 'knowledge', 'study'],
  graduation: ['graduation', 'cap', 'degree', 'graduate', 'education', 'school', 'university'],
  login: ['login', 'sign-in', 'signin', 'enter', 'access', 'authenticate'],
  logout: ['logout', 'sign-out', 'signout', 'exit', 'leave'],
  register: ['register', 'sign-up', 'signup', 'join', 'enroll', 'subscribe'],
  subscribe: ['subscribe', 'follow', 'join', 'register', 'notification', 'bell'],
  cal: ['cal', 'calendar', 'date', 'schedule'],
  notif: ['notif', 'notification', 'bell', 'alert'],
  del: ['del', 'delete', 'trash', 'remove', 'bin', 'erase'],
  rem: ['rem', 'remove', 'trash', 'delete', 'erase'],
  conf: ['conf', 'config', 'settings', 'configure', 'preferences'],
  mag: ['mag', 'magnifier', 'magnify', 'search', 'find', 'magic'],
  calc: ['calc', 'calculator', 'compute', 'calculate', 'math'],
  math: ['math', 'mathematics', 'calculate', 'calc', 'calculator'],
  doc: ['doc', 'document', 'file', 'text', 'paper'],
  cam: ['cam', 'camera', 'photo', 'video', 'record'],
  pref: ['pref', 'preferences', 'settings', 'options'],
  warn: ['warn', 'warning', 'alert', 'caution', 'danger'],
  err: ['err', 'error', 'danger', 'warning', 'fail'],
  noti: ['noti', 'notification', 'bell', 'alert', 'notify'],
  mini: ['mini', 'minimal', 'minimalistic', 'small', 'simple'],
  max: ['max', 'maximize', 'maximum', 'full', 'fullscreen'],
  rect: ['rect', 'rectangle', 'square', 'box'],
  curve: ['curve', 'curved', 'bend', 'arc', 'semicircle'],
  loc: ['loc', 'location', 'pin', 'map', 'place', 'address'],
  pos: ['pos', 'position', 'location', 'pin', 'map', 'place'],
  geo: ['geo', 'geography', 'location', 'map', 'pin', 'earth'],
  happy: ['happy', 'smile', 'joy', 'face', 'emoji', 'laugh', 'cheerful', 'grin'],
  sad: ['sad', 'frown', 'cry', 'upset', 'unhappy', 'face', 'emoji', 'depressed'],
  smile: ['smile', 'happy', 'joy', 'face', 'emoji', 'laugh', 'cheerful'],
  angry: ['angry', 'mad', 'frustrated', 'face', 'emoji', 'annoyed'],
  emoji: ['emoji', 'emoticon', 'smile', 'face', 'happy', 'sad', 'feeling'],
  '1': ['1', 'one', 'single', 'first'],
  '2': ['2', 'two', 'second', 'double', 'pair', 'dual'],
  '3': ['3', 'three', 'third', 'triple'],
  '4': ['4', 'four', 'fourth'],
  '5': ['5', 'five', 'fifth'],
  zero: ['zero', '0', 'null', 'none', 'nothing'],
  hand: ['hand', 'finger', 'point', 'gesture', 'touch', 'click', 'tap', 'swipe'],
  touch: ['touch', 'hand', 'finger', 'tap', 'gesture'],
  click: ['click', 'tap', 'hand', 'finger', 'cursor', 'select'],
  cursor: ['cursor', 'pointer', 'mouse', 'arrow', 'click', 'select'],
  drag: ['drag', 'move', 'grab', 'hold', 'hand'],
  zoom: ['zoom', 'magnify', 'search', 'scale', 'enlarge', 'expand'],
  scan: ['scan', 'scanner', 'search', 'find', 'detect', 'qr', 'barcode'],
  qr: ['qr', 'qrcode', 'barcode', 'scan', 'scanner', 'code'],
  barcode: ['barcode', 'qr', 'scan', 'scanner', 'code'],
  bookmark: ['bookmark', 'favorite', 'save', 'bookmark', 'tag', 'ribbon'],
  uuid: ['uuid', 'unique', 'id', 'identifier', 'hash'],
  hash: ['hash', 'hashtag', 'number', 'pound', '#', 'tag'],
  cpu: ['cpu', 'processor', 'chip', 'microchip', 'computer', 'hardware', 'server'],
  monitor: ['monitor', 'screen', 'display', 'desktop', 'computer', 'lcd', 'led'],
  laptop: ['laptop', 'computer', 'notebook', 'macbook', 'portable', 'chromebook'],
  tablet: ['tablet', 'ipad', 'device', 'mobile', 'screen'],
  keyboard: ['keyboard', 'type', 'key', 'typing', 'input', 'keys'],
  mouse: ['mouse', 'cursor', 'click', 'pointer', 'computer', 'device'],
  printer: ['printer', 'print', 'output', 'paper', 'device', 'laser'],
  projector: ['projector', 'presentation', 'display', 'screen', 'slides'],
  vr: ['vr', 'virtual', 'reality', 'headset', 'goggles', '3d', 'ar'],
  ar: ['ar', 'augmented', 'reality', 'vr', 'vision', 'camera'],
  hologram: ['hologram', '3d', 'projection', 'virtual', 'ar', 'vr'],
  checkout: ['checkout', 'cart', 'payment', 'buy', 'purchase', 'order'],
  order: ['order', 'checkout', 'cart', 'shipping', 'delivery', 'purchase'],
  delivery: ['delivery', 'shipping', 'truck', 'van', 'package', 'courier', 'order'],
  shipping: ['shipping', 'delivery', 'truck', 'package', 'order', 'transport'],
  coupon: ['coupon', 'discount', 'voucher', 'code', 'promo', 'sale', 'offer'],
  discount: ['discount', 'sale', 'offer', 'coupon', 'promo', 'deal', 'saving'],
  sale: ['sale', 'discount', 'offer', 'deal', 'promo', 'price', 'tag'],
  christmas: ['christmas', 'xmas', 'santa', 'gift', 'tree', 'holiday', 'celebration', 'snow'],
  holiday: ['holiday', 'vacation', 'travel', 'trip', 'vacation', 'celebration', 'festival'],
  birthday: ['birthday', 'cake', 'candle', 'gift', 'present', 'party', 'celebrate'],
  party: ['party', 'celebrate', 'confetti', 'balloon', 'music', 'dance', 'festival'],
  celebrate: ['celebrate', 'party', 'award', 'trophy', 'confetti', 'star', 'sparkle'],
  wedding: ['wedding', 'marriage', 'ring', 'heart', 'couple', 'bride', 'groom'],
  recycle: ['recycle', 'recycling', 'green', 'eco', 'environment', 'sustainable', 'earth'],
  eco: ['eco', 'green', 'environment', 'nature', 'earth', 'leaf', 'recycle'],
  tree: ['tree', 'nature', 'plant', 'forest', 'green', 'environment', 'leaf', 'wood'],
  flower: ['flower', 'nature', 'plant', 'garden', 'bloom', 'blossom', 'rose'],
  plant: ['plant', 'tree', 'nature', 'leaf', 'green', 'garden', 'flower'],
  garden: ['garden', 'plant', 'flower', 'nature', 'tree', 'grow'],
  mountain: ['mountain', 'hill', 'nature', 'landscape', 'peak', 'outdoor', 'adventure'],
  travel: ['travel', 'trip', 'vacation', 'holiday', 'adventure', 'journey', 'explore'],
  airport: ['airport', 'plane', 'flight', 'travel', 'departure', 'arrival', 'luggage'],
  luggage: ['luggage', 'baggage', 'suitcase', 'bag', 'travel', 'trip', 'pack'],
  suitcase: ['suitcase', 'luggage', 'bag', 'travel', 'trip', 'baggage'],
  tent: ['tent', 'camping', 'camp', 'outdoor', 'nature', 'adventure', 'sleeping'],
  camping: ['camping', 'camp', 'tent', 'outdoor', 'nature', 'adventure', 'hiking'],
  passport: ['passport', 'travel', 'visa', 'id', 'identification', 'document', 'border'],
  hotel: ['hotel', 'lodging', 'stay', 'accommodation', 'travel', 'building', 'hostel'],
  bank: ['bank', 'building', 'finance', 'money', 'banking', 'financial', 'institution'],
  finance: ['finance', 'money', 'bank', 'financial', 'dollar', 'currency', 'investment'],
  invest: ['invest', 'investment', 'stock', 'market', 'finance', 'money', 'growth', 'chart'],
  stock: ['stock', 'market', 'trade', 'finance', 'money', 'investment', 'share'],
  tax: ['tax', 'finance', 'money', 'government', 'return', 'document', 'file'],
  invoice: ['invoice', 'bill', 'receipt', 'payment', 'document', 'finance', 'money'],
  bill: ['bill', 'invoice', 'receipt', 'payment', 'document', 'finance'],
  receipt: ['receipt', 'bill', 'invoice', 'payment', 'purchase', 'document'],
  credit: ['credit', 'card', 'payment', 'money', 'finance', 'debit', 'bank'],
  'credit card': ['credit-card', 'credit', 'card', 'payment', 'money', 'debit'],
  headphone: ['headphone', 'headphones', 'earphone', 'earbuds', 'audio', 'listening', 'music', 'podcast'],
  earbuds: ['earbuds', 'headphone', 'earphone', 'audio', 'music', 'podcast'],
  podcast: ['podcast', 'audio', 'mic', 'microphone', 'listen', 'radio', 'episode'],
  recorder: ['recorder', 'record', 'voice', 'audio', 'mic', 'tape'],
  football: ['football', 'soccer', 'sport', 'ball', 'game', 'goal', 'field'],
  basketball: ['basketball', 'ball', 'sport', 'game', 'hoop', 'court', 'nba'],
  tennis: ['tennis', 'sport', 'ball', 'racket', 'game', 'court'],
  baseball: ['baseball', 'ball', 'sport', 'game', 'bat', 'glove', 'mlb'],
  volleyball: ['volleyball', 'ball', 'sport', 'game', 'net', 'court'],
  golf: ['golf', 'sport', 'club', 'ball', 'course', 'putt', 'drive'],
  swimming: ['swimming', 'swim', 'pool', 'water', 'sport', 'ocean', 'beach'],
  hiking: ['hiking', 'hike', 'trail', 'mountain', 'nature', 'outdoor', 'walk'],
  yoga: ['yoga', 'meditation', 'exercise', 'fitness', 'stretch', 'flexibility', 'pose'],
  exercise: ['exercise', 'workout', 'fitness', 'gym', 'sport', 'train', 'training'],
  briefcase: ['briefcase', 'bag', 'work', 'job', 'career', 'business', 'office', 'professional'],
  business: ['business', 'work', 'office', 'briefcase', 'career', 'corporate', 'professional'],
  office: ['office', 'work', 'building', 'desk', 'corporate', 'chair', 'worker'],
  meeting: ['meeting', 'conference', 'presentation', 'team', 'discussion', 'collab', 'board'],
  interview: ['interview', 'meeting', 'job', 'career', 'talk', 'conversation', 'chat'],
  resume: ['resume', 'cv', 'job', 'document', 'application', 'career', 'profile'],
  worker: ['worker', 'employee', 'staff', 'team', 'professional', 'job', 'career'],
  boss: ['boss', 'manager', 'leader', 'CEO', 'chief', 'director', 'executive'],
  'work from home': ['work-from-home', 'wfh', 'remote', 'home', 'laptop', 'work'],
  hammer: ['hammer', 'tool', 'build', 'construction', 'repair', 'fix'],
  wrench: ['wrench', 'tool', 'spanner', 'fix', 'repair', 'mechanical', 'settings', 'maintenance'],
  screwdriver: ['screwdriver', 'tool', 'fix', 'repair', 'construction', 'build'],
  saw: ['saw', 'tool', 'cut', 'construction', 'wood', 'carpenter'],
  construction: ['construction', 'build', 'building', 'tool', 'hard-hat', 'helmet', 'industry'],
  helmet: ['helmet', 'safety', 'protection', 'hard-hat', 'construction', 'head'],
  input: ['input', 'text', 'field', 'form', 'type', 'typing', 'edit', 'entry'],
  text: ['text', 'type', 'input', 'write', 'edit', 'content', 'letter', 'word'],
  form: ['form', 'input', 'field', 'questionnaire', 'application', 'survey'],
  'search icon': ['search', 'magnifier', 'find'],
  'home icon': ['home', 'house'],
  'user icon': ['user', 'person'],
  'arrow left': ['arrow-left', 'left', 'back', 'chevron-left'],
  'arrow right': ['arrow-right', 'right', 'next', 'chevron-right'],
  'arrow up': ['arrow-up', 'up', 'chevron-up'],
  'arrow down': ['arrow-down', 'down', 'chevron-down'],
  'x close': ['x', 'close', 'cancel', 'dismiss'],
  'up arrow': ['arrow-up', 'up', 'chevron-up'],
  'down arrow': ['arrow-down', 'down', 'chevron-down'],
  'left arrow': ['arrow-left', 'left', 'back', 'chevron-left'],
  'right arrow': ['arrow-right', 'right', 'next', 'chevron-right'],
  'go back': ['back', 'arrow-left', 'left', 'return', 'chevron-left'],
  'go next': ['next', 'arrow-right', 'right', 'forward', 'chevron-right'],
  'scroll down': ['scroll', 'down', 'arrow-down', 'chevron-down'],
  'scroll up': ['scroll', 'up', 'arrow-up', 'chevron-up'],
  'sound off': ['sound-off', 'mute', 'volume-mute', 'no-sound', 'silent'],
  'sound on': ['volume', 'sound', 'speaker'],
  'turn off': ['power', 'off', 'switch', 'shutdown'],
  'turn on': ['power', 'on', 'switch', 'start'],
  'full screen': ['fullscreen', 'full-screen', 'maximize', 'expand', 'enlarge'],
  'log in': ['login', 'sign-in', 'enter'],
  'log out': ['logout', 'sign-out', 'exit'],
  'sign in': ['login', 'sign-in', 'enter', 'access'],
  'sign out': ['logout', 'sign-out', 'exit'],
  'no wifi': ['wifi-off', 'no-wifi', 'wifi-slash', 'offline'],
  'no internet': ['wifi-off', 'offline', 'disconnected'],
  'no signal': ['wifi-off', 'signal-slash', 'offline'],
  'no entry': ['no-entry', 'forbidden', 'blocked', 'stop', 'prohibited', 'restricted'],
  'do not disturb': ['do-not-disturb', 'dnd', 'moon', 'sleep', 'silent', 'quiet'],
  'air conditioner': ['air-conditioner', 'ac', 'climate', 'cooling', 'hvac', 'cold'],
  'air conditioning': ['air-conditioning', 'ac', 'ac2', 'climate', 'cooling', 'cold'],
  'user circle': ['user-circle', 'user-round', 'profile-circle', 'avatar'],
  'user square': ['user-square', 'profile-square'],
  'check circle': ['check-circle', 'success-circle', 'verified', 'confirm-circle'],
  'check square': ['check-square', 'checkbox', 'success-square'],
  'alert circle': ['alert-circle', 'warning-circle', 'danger-circle'],
  'alert triangle': ['alert-triangle', 'warning', 'danger-triangle'],
  'info circle': ['info-circle', 'information-circle'],
  'question circle': ['question-circle', 'help-circle'],
  'plus circle': ['add-circle', 'plus-circle'],
  'plus square': ['add-square', 'plus-square'],
  'minus circle': ['minus-circle', 'subtract-circle'],
  'minus square': ['minus-square', 'subtract-square'],
  'x circle': ['x-circle', 'close-circle', 'cancel-circle', 'remove-circle'],
  'x square': ['x-square', 'close-square', 'cancel-square', 'remove-square'],
  'heart outline': ['heart', 'heart-outline'],
  'heart filled': ['heart', 'heart-filled', 'heart-bold'],
  'star outline': ['star', 'star-outline', 'star-empty'],
  'star filled': ['star-filled', 'star-bold', 'star-solid'],
  'trash can': ['trash', 'trash-can', 'delete', 'bin'],
  'shopping bag': ['shopping-bag', 'bag', 'cart', 'shopping', 'store-bag'],
  'id card': ['id-card', 'id', 'identification', 'badge'],
  'gift card': ['gift-card', 'gift', 'present-card'],
  'menu bar': ['menu', 'bars', 'hamburger', 'nav'],
  'menu dots': ['menu-dots', 'more', 'dots', 'ellipsis', 'kebab'],
  'three dots': ['more', 'dots', 'ellipsis', 'menu-dots', 'kebab', 'three-dots'],
  'more options': ['more', 'more-options', 'ellipsis', 'dots'],
  'loading spinner': ['loading', 'spinner', 'loader', 'circle'],
  'arrow up circle': ['arrow-up-circle', 'chevron-up-circle'],
  'arrow down circle': ['arrow-down-circle', 'chevron-down-circle'],
  'arrow left circle': ['arrow-left-circle', 'chevron-left-circle'],
  'arrow right circle': ['arrow-right-circle', 'chevron-right-circle'],
  'circle check': ['check-circle', 'success-circle', 'verified'],
  'circle x': ['x-circle', 'close-circle', 'cancel-circle'],
  'circle plus': ['plus-circle', 'add-circle'],
  'circle minus': ['minus-circle', 'subtract-circle'],
  'circle alert': ['alert-circle', 'warning-circle'],
  'circle info': ['info-circle', 'information-circle'],
  'circle question': ['question-circle', 'help-circle'],
  'circle play': ['play-circle', 'video-circle'],
  'circle pause': ['pause-circle', 'stop-circle'],
  'circle stop': ['stop-circle', 'stop'],
  'notification bell': ['bell', 'notification', 'alert'],
  'notifications off': ['bell-off', 'notification-off', 'notifications-off', 'dnd'],
  'volume up': ['volume-up', 'volume-high', 'speaker'],
  'volume down': ['volume-down', 'volume-low', 'speaker-low'],
  'volume off': ['volume-off', 'mute', 'no-sound', 'silent'],
  'play button': ['play', 'play-button', 'video-play', 'start'],
  'pause button': ['pause', 'pause-button', 'pause-circle'],
  'stop button': ['stop', 'stop-button', 'stop-circle'],
  'next track': ['next', 'skip-next', 'forward', 'skip'],
  'previous track': ['previous', 'skip-previous', 'backward', 'rewind'],
  'rewind back': ['rewind', 'backward', 'skip-back'],
  'fast forward': ['fast-forward', 'forward', 'skip-forward'],
  'phone call': ['phone', 'call', 'phone-call', 'phone-ringing', 'incoming'],
  'phone off': ['phone-off', 'phone-slash', 'call-end', 'reject'],
  'video call': ['video-call', 'video', 'camera', 'facetime', 'zoom'],
  'video off': ['video-off', 'camera-off', 'no-video'],
  'camera photo': ['camera', 'photo', 'picture', 'snap'],
  'take photo': ['camera', 'photo', 'shutter', 'snap'],
  'lock password': ['lock', 'password', 'secure', 'lock-key'],
  'unlock open': ['unlock', 'lock-opened', 'open-lock'],
  'map pin': ['map-pin', 'pin', 'map-point', 'location'],
  'map location': ['map', 'location', 'pin', 'map-point', 'place'],
  'clock time': ['clock', 'time', 'watch'],
  'alarm clock': ['alarm-clock', 'alarm', 'clock', 'alarm2'],
  'date calendar': ['calendar', 'date', 'calendar-date'],
  'user profile': ['user', 'profile', 'person', 'account'],
  'group team': ['group', 'team', 'users', 'people'],
  'download file': ['download', 'file-download', 'save'],
  'upload file': ['upload', 'file-upload'],
  'new file': ['file-add', 'new-file', 'file-plus', 'create-file', 'add-file'],
  'new folder': ['folder-add', 'new-folder', 'folder-plus', 'create-folder'],
  'delete file': ['file-remove', 'delete-file', 'trash', 'remove-file'],
  'search find': ['search', 'find', 'magnifier', 'lookup'],
  'email mail': ['email', 'mail', 'envelope', 'letter'],
  'send message': ['send', 'message', 'chat-send', 'send-message'],
  'chat message': ['chat', 'message', 'chat-bubble', 'text-chat'],
  'settings gear': ['settings', 'gear', 'cog', 'preferences'],
  'help support': ['help', 'support', 'info', 'question', 'faq'],
  'edit pencil': ['edit', 'pencil', 'pen', 'write'],
  'link url': ['link', 'url', 'chain', 'hyperlink'],
  'share social': ['share', 'share-social', 'social'],
  'bookmark save': ['bookmark', 'save', 'favorite', 'ribbon'],
  'star rating': ['star', 'rating', 'stars', 'review'],
  'heart like': ['heart', 'like', 'love', 'favorite'],
  'trash delete': ['trash', 'delete', 'remove', 'bin', 'erase'],
  'folder directory': ['folder', 'directory', 'file-manager'],
  'file document': ['file', 'document', 'doc', 'paper', 'text'],
  'save floppy': ['save', 'floppy', 'disk', 'floppy-disk'],
  'print printer': ['print', 'printer'],
  'wifi internet': ['wifi', 'internet', 'wireless', 'network'],
  'bluetooth wireless': ['bluetooth', 'wireless'],
  'battery charge': ['battery', 'charge', 'charging', 'power'],
  'power off': ['power-off', 'power', 'switch-off', 'shutdown'],
  'reset restart': ['reset', 'restart', 'refresh', 'reload'],
  'sun light': ['sun', 'light', 'sunny', 'brightness', 'daylight'],
  'moon dark': ['moon', 'dark', 'night', 'dark-mode', 'sleep'],
  'weather forecast': ['weather', 'forecast', 'sun', 'rain', 'cloud', 'snow'],
  'rain drop': ['rain', 'drop', 'water', 'raindrop', 'weather'],
  'snow flake': ['snow', 'snowflake', 'ice', 'winter'],
  'hot temperature': ['temperature', 'hot', 'heat', 'thermometer', 'warm'],
  'cold temperature': ['temperature', 'cold', 'thermometer', 'cool', 'freeze'],
  'direction sign': ['direction', 'sign', 'signpost', 'road-sign'],
  'security shield': ['security', 'shield', 'safe', 'protect'],
  'warning alert': ['warning', 'alert', 'caution', 'danger'],
  'check mark': ['check', 'tick', 'checkmark', 'correct', 'done'],
  'x mark': ['x', 'x-mark', 'close', 'cancel', 'remove'],
  'plus add': ['plus', 'add', 'new', 'create'],
  'minus subtract': ['minus', 'subtract', 'remove'],
  'pie chart': ['pie-chart', 'chart', 'graph-pie', 'pie'],
  'bar chart': ['bar-chart', 'bar-graph', 'chart-bar', 'histogram'],
  'line chart': ['line-chart', 'chart-line', 'graph'],
  'home house': ['home', 'house'],
  'navigation menu': ['navigation', 'menu', 'nav', 'hamburger', 'drawer'],
  'cart shopping': ['cart', 'shopping', 'shopping-cart', 'bag', 'basket'],
  'wallet money': ['wallet', 'money', 'finance', 'purse'],
  'payment card': ['payment', 'card', 'credit-card', 'debit-card'],
  'coin money': ['coin', 'money', 'cash', 'currency'],
  'dollar currency': ['dollar', 'money', 'currency', 'finance'],
  'euro currency': ['euro', 'money', 'currency', 'finance'],
  'calendar date': ['calendar', 'date', 'day', 'schedule', 'event'],
  'clock timer': ['clock', 'timer', 'stopwatch', 'time'],
  'alarm wake': ['alarm', 'wake', 'alarm-clock', 'morning'],
  'bell ring': ['bell', 'ring', 'notification', 'alert'],
  'message chat': ['message', 'chat', 'text', 'conversation'],
  'email envelope': ['email', 'envelope', 'mail', 'letter'],
  'video camera': ['video', 'camera', 'movie', 'film', 'record'],
  'music note': ['music', 'note', 'music-note', 'song', 'audio'],
  'headphone listen': ['headphone', 'headphones', 'listen', 'audio', 'music'],
  'microphone speak': ['microphone', 'mic', 'speak', 'voice', 'talk'],
  'presentation slide': ['presentation', 'slide', 'screen', 'projector', 'monitor'],
  'laptop computer': ['laptop', 'computer', 'notebook', 'macbook'],
  'desktop computer': ['desktop', 'computer', 'monitor', 'pc', 'tower'],
  'mobile phone': ['mobile', 'phone', 'smartphone', 'cellphone'],
  'tablet device': ['tablet', 'device', 'ipad', 'pad'],
  'game controller': ['game-controller', 'gamepad', 'gaming', 'joystick'],
  'vr headset': ['vr-headset', 'vr', 'virtual-reality', 'goggles', 'headset'],
  'drone fly': ['drone', 'fly', 'aerial', 'quadcopter', 'camera'],
  'robot ai': ['robot', 'ai', 'artificial-intelligence', 'machine', 'android'],
  'alt version': ['2', 'alt', 'alternative', 'variant', 'version-2'],
  seach: ['search', 'find', 'magnifier', 'magnify'],
  searc: ['search', 'find', 'magnifier'],
  settngs: ['settings', 'gear', 'cog', 'preferences'],
  settng: ['settings', 'gear', 'cog'],
  prefrences: ['preferences', 'settings', 'options'],
  notfication: ['notification', 'bell', 'alert'],
  notifcation: ['notification', 'bell', 'alert'],
  calender: ['calendar', 'date', 'schedule'],
  calandar: ['calendar', 'date', 'schedule'],
  massge: ['message', 'chat', 'msg'],
  messge: ['message', 'chat', 'msg'],
  delet: ['delete', 'trash', 'remove'],
  delte: ['delete', 'trash', 'remove'],
  arror: ['arrow', 'chevron', 'direction'],
  carot: ['caret', 'chevron', 'arrow', 'dropdown'],
  hart: ['heart', 'love', 'favorite'],
  profle: ['profile', 'user', 'person', 'account'],
  proflie: ['profile', 'user', 'person', 'account'],
  thumb: ['thumb', 'thumbs', 'like', 'up', 'down'],
  colse: ['close', 'x', 'dismiss', 'cancel'],
  clos: ['close', 'x', 'dismiss', 'cancel'],
  open: ['open', 'folder-open', 'lock-opened', 'expand'],
  opne: ['open', 'expand', 'folder-open'],
  downlad: ['download', 'save'],
  uplaod: ['upload', 'import'],
  upoad: ['upload', 'import'],
  downoad: ['download', 'save'],
  notifis: ['notification', 'bell', 'alert'],
  'menu icon': ['menu', 'hamburger'],
  'settings icon': ['settings', 'gear'],
  'close icon': ['close', 'x', 'cancel'],
  'delete icon': ['trash', 'delete', 'remove'],
  'edit icon': ['edit', 'pencil', 'pen'],
  'save icon': ['save', 'download', 'floppy'],
  'share icon': ['share', 'send'],
  'upload icon': ['upload', 'import'],
  'download icon': ['download', 'save'],
  'print icon': ['print', 'printer'],
  'lock icon': ['lock', 'secure'],
  'unlock icon': ['unlock', 'lock-opened'],
  'bell icon': ['bell', 'notification', 'alert'],
  'heart icon': ['heart', 'love', 'favorite'],
  'star icon': ['star', 'rating'],
  'cart icon': ['cart', 'shopping', 'bag'],
  'trash icon': ['trash', 'delete', 'bin'],
  'phone icon': ['phone', 'call', 'mobile'],
  'mail icon': ['mail', 'email', 'envelope'],
  'chat icon': ['chat', 'message', 'bubble'],
  'calendar icon': ['calendar', 'date'],
  'clock icon': ['clock', 'time', 'watch'],
  'camera icon': ['camera', 'photo'],
  'video icon': ['video', 'camera', 'film'],
  'music icon': ['music', 'note', 'song'],
  'map icon': ['map', 'location', 'pin'],
  'globe icon': ['globe', 'world', 'earth'],
  'shield icon': ['shield', 'security', 'safe'],
  'wifi icon': ['wifi', 'internet', 'wireless'],
  'battery icon': ['battery', 'power', 'charge'],
  'sun icon': ['sun', 'light', 'brightness'],
  'moon icon': ['moon', 'night', 'dark'],
  'cloud icon': ['cloud', 'weather'],
  'rain icon': ['rain', 'weather', 'drop'],
  'snow icon': ['snow', 'snowflake', 'winter'],
  'fire icon': ['fire', 'flame'],
  'water icon': ['water', 'drop', 'droplet'],
  'gift icon': ['gift', 'present', 'box'],
  'tag icon': ['tag', 'label', 'price'],
  'pin icon': ['pin', 'map-point', 'location'],
  'book icon': ['book', 'read', 'library'],
  'file icon': ['file', 'document', 'paper', 'doc'],
  'folder icon': ['folder', 'directory'],
  'image icon': ['image', 'gallery', 'photo', 'picture'],
  'flag icon': ['flag', 'country'],
  'link icon': ['link', 'url', 'chain'],
  'code icon': ['code', 'coding', 'programming'],
  'terminal icon': ['terminal', 'console', 'command'],
  'chart icon': ['chart', 'graph', 'stats'],
  'database icon': ['database', 'data', 'storage'],
  'server icon': ['server', 'host', 'cloud'],
  'car icon': ['car', 'vehicle', 'auto'],
  'bus icon': ['bus', 'vehicle', 'transport'],
  'plane icon': ['plane', 'airplane', 'flight'],
  'train icon': ['train', 'railway', 'subway'],
  'bike icon': ['bike', 'bicycle', 'cycle'],
  'food icon': ['food', 'meal', 'dining'],
  'drink icon': ['drink', 'beverage', 'cup'],
  'coffee icon': ['coffee', 'drink', 'mug', 'cup'],
  'smile icon': ['smile', 'happy', 'face', 'emoji'],
  'check icon': ['check', 'tick', 'success', 'done'],
  'plus icon': ['plus', 'add', 'new', 'create'],
  'minus icon': ['minus', 'subtract', 'remove'],
  'arrow icon': ['arrow', 'chevron', 'direction'],
  'filter icon': ['filter', 'sort', 'narrow'],
  'refresh icon': ['refresh', 'reload', 'restart', 'sync'],
  'info icon': ['info', 'information', 'help'],
  'help icon': ['help', 'info', 'question', 'support'],
  'warning icon': ['warning', 'alert', 'caution', 'danger'],
  'question icon': ['question', 'help', 'info', 'support'],
  'logout icon': ['logout', 'sign-out', 'exit'],
  'login icon': ['login', 'sign-in', 'enter'],

  // ─── Text formatting ──────────────────────────────────────────────────
  bold: ['bold', 'strong', 'emphasize', 'heavy'],
  italic: ['italic', 'italics', 'emphasize', 'slanted', 'oblique'],
  underline: ['underline', 'underscore', 'line'],
  strikethrough: ['strikethrough', 'strike', 'cross-out'],
  align: ['align', 'alignment', 'justify', 'text-align'],
  'align left': ['align-left', 'left-align', 'text-left'],
  'align right': ['align-right', 'right-align', 'text-right'],
  'align center': ['align-center', 'center-align', 'text-center', 'centered'],
  'align justify': ['align-justify', 'justify', 'justified'],
  font: ['font', 'typeface', 'typography', 'text'],
  indent: ['indent', 'indentation', 'tab', 'outdent'],
  outdent: ['outdent', 'unindent', 'dedent'],
  subscript: ['subscript', 'sub', 'lower'],
  superscript: ['superscript', 'super', 'upper', 'exponent'],
  quote: ['quote', 'blockquote', 'citation', 'quotation', 'testimonial'],

  // ─── Layout / UI ──────────────────────────────────────────────────────
  sidebar: ['sidebar', 'side-panel', 'drawer', 'panel', 'side-menu'],
  toolbar: ['toolbar', 'tool-bar', 'ribbon', 'action-bar'],
  navbar: ['navbar', 'nav-bar', 'navigation-bar', 'header', 'top-bar'],
  footer: ['footer', 'bottom-bar', 'page-end'],
  divider: ['divider', 'separator', 'rule', 'hr', 'line'],
  spacing: ['spacing', 'space', 'gap', 'padding', 'margin'],
  layout: ['layout', 'template', 'structure', 'arrangement', 'composition'],
  element: ['element', 'component', 'block', 'widget'],
  frame: ['frame', 'border', 'outline', 'container', 'box'],
  layers: ['layers', 'stack', 'overlap', 'z-index', 'ordering'],
  empty: ['empty', 'blank', 'void', 'none', 'nothing', 'no-content'],

  // ─── View / visibility ────────────────────────────────────────────────
  eye: ['eye', 'view', 'visibility', 'visible', 'show', 'preview', 'look'],
  'eye off': ['eye-off', 'eye-slash', 'hide', 'invisible', 'hidden', 'conceal'],
  hide: ['hide', 'hidden', 'invisible', 'conceal', 'eye-off'],
  show: ['show', 'reveal', 'display', 'unhide', 'visible', 'view'],
  visible: ['visible', 'shown', 'displayed', 'eye', 'view'],
  invisible: ['invisible', 'hidden', 'eye-off', 'concealed', 'not-visible'],

  // ─── Archive / storage ────────────────────────────────────────────────
  archive: ['archive', 'box', 'storage', 'pack', 'bundle', 'package', 'compress'],
  unarchive: ['unarchive', 'extract', 'unpack', 'uncompress', 'open'],
  zip: ['zip', 'compressed', 'archive', 'compress'],
  unzip: ['unzip', 'extract', 'decompress', 'expand'],

  // ─── Edit / tools ────────────────────────────────────────────────────
  eraser: ['eraser', 'erase', 'remove', 'rubber', 'delete'],
  bucket: ['bucket', 'fill', 'paint', 'color-fill', 'pour'],
  ruler: ['ruler', 'measure', 'measurement', 'scale', 'size'],
  redo: ['redo', 'forward', 'repeat', 'reapply'],
  undo: ['undo', 'reverse', 'revert', 'rollback'],
  pipette: ['pipette', 'dropper', 'eyedropper', 'color-pick', 'sample'],
  mirror: ['mirror', 'flip', 'reflect', 'reverse'],

  // ─── Shapes (extended) ────────────────────────────────────────────────
  cube: ['cube', 'box', 'block', '3d', 'dice', 'solid'],
  cone: ['cone', 'pyramid', 'taper', 'pointed'],
  cylinder: ['cylinder', 'tube', 'pipe', 'round'],
  diamond: ['diamond', 'gem', 'jewel', 'rhombus', 'crystal', 'shape'],
  hexagon: ['hexagon', 'hex', '6-sided', 'honeycomb'],
  octagon: ['octagon', 'octo', '8-sided', 'stop'],
  crescent: ['crescent', 'moon', 'half-moon', 'curved'],
  cross: ['cross', 'plus', 'x', 'multiply', 'sign'],
  infinity: ['infinity', 'loop', 'eternal', 'endless', 'unlimited', 'infinite'],
  omega: ['omega', 'symbol', 'greek', 'end'],
  '3d': ['3d', 'three-d', 'three-dimensional', 'cube', 'isometric'],
  diagonal: ['diagonal', 'angled', 'slanted', 'bias'],
  dotted: ['dotted', 'dashed', 'stippled', 'dots', 'dashed-line'],
  dashed: ['dashed', 'dotted', 'broken-line', 'dash'],

  // ─── Map / travel extended ────────────────────────────────────────────
  radar: ['radar', 'scan', 'detect', 'tracking', 'signal', 'sonar'],
  streets: ['streets', 'street', 'road', 'map', 'navigation', 'city'],
  suspension: ['suspension', 'bridge', 'cable', 'structure', 'road'],
  direct: ['direct', 'straight', 'non-stop', 'express', 'through'],

  // ─── Weather extended ────────────────────────────────────────────────
  fog: ['fog', 'mist', 'haze', 'cloudy', 'visibility', 'weather'],
  hail: ['hail', 'ice', 'storm', 'weather', 'precipitation'],
  tornado: ['tornado', 'twister', 'storm', 'weather', 'wind'],
  hurricane: ['hurricane', 'cyclone', 'typhoon', 'storm', 'weather'],
  humidity: ['humidity', 'moisture', 'damp', 'wet', 'weather'],
  rainbow: ['rainbow', 'colorful', 'prism', 'spectrum', 'weather'],

  // ─── Nature extended ─────────────────────────────────────────────────
  volcano: ['volcano', 'mountain', 'lava', 'eruption', 'nature'],
  desert: ['desert', 'sand', 'arid', 'dry', 'landscape', 'nature'],
  island: ['island', 'beach', 'tropical', 'paradise', 'ocean'],
  beach: ['beach', 'sand', 'ocean', 'sea', 'coast', 'shore', 'vacation'],
  river: ['river', 'stream', 'water', 'flow', 'nature'],
  lake: ['lake', 'water', 'pond', 'nature', 'scenic'],
  waterfall: ['waterfall', 'falls', 'water', 'cascade', 'nature'],
  forest: ['forest', 'woods', 'trees', 'nature', 'wild'],
  seed: ['seed', 'sprout', 'grow', 'plant', 'nature', 'beginning'],

  // ─── Technology extended ──────────────────────────────────────────────
  plug: ['plug', 'power', 'connect', 'charger', 'adapter', 'cable'],
  usb: ['usb', 'cable', 'connect', 'port', 'drive', 'flash'],
  'usb drive': ['usb-drive', 'usb', 'flash-drive', 'thumb-drive', 'storage', 'pendrive'],
  bug: ['bug', 'bug-report', 'issue', 'error', 'glitch', 'problem', 'debug'],
  ssd: ['ssd', 'drive', 'storage', 'disk', 'solid-state', 'hard-drive'],
  'hard drive': ['hard-drive', 'hdd', 'ssd', 'storage', 'disk', 'drive'],
  chip: ['chip', 'microchip', 'processor', 'cpu', 'silicon', 'semiconductor'],
  gpu: ['gpu', 'graphics', 'video-card', 'graphics-card'],
  ram: ['ram', 'memory', 'storage', 'dimm'],
  motherboard: ['motherboard', 'mother-board', 'mainboard', 'system-board', 'pcb'],
  sensor: ['sensor', 'detector', 'probe', 'scanner', 'reader'],
  firmware: ['firmware', 'software', 'os', 'system', 'embedded'],
  pixel: ['pixel', 'dot', 'point', 'resolution'],
  resolution: ['resolution', 'quality', 'sharpness', 'clarity', 'hd', '4k'],
  hz: ['hz', 'hertz', 'refresh-rate', 'frequency', 'rate'],
  latency: ['latency', 'delay', 'lag', 'ping', 'response-time'],
  bandwidth: ['bandwidth', 'speed', 'throughput', 'internet', 'connection'],
  protocol: ['protocol', 'standard', 'format', 'specification', 'rule'],

  // ─── Network ──────────────────────────────────────────────────────────
  router: ['router', 'network', 'wifi', 'internet', 'modem', 'gateway'],
  modem: ['modem', 'router', 'internet', 'network', 'broadband'],
  firewall: ['firewall', 'security', 'protect', 'network', 'shield'],
  proxy: ['proxy', 'forward', 'relay', 'gateway', 'intermediary'],
  dns: ['dns', 'domain', 'name-server', 'internet', 'network'],
  vpn: ['vpn', 'network', 'secure', 'tunnel', 'private'],
  'cloud computing': ['cloud', 'computing', 'iaas', 'paas', 'saas', 'hosting'],

  // ─── Media / AV ───────────────────────────────────────────────────────
  clapperboard: ['clapperboard', 'clapboard', 'film', 'movie', 'director', 'action', 'cinema'],
  filmstrip: ['filmstrip', 'film', 'movie', 'reel', 'celluloid'],
  screen: ['screen', 'display', 'monitor', 'view', 'show'],
  widescreen: ['widescreen', 'wide', 'cinema', 'aspect-ratio', '16-9'],
  thumbnail: ['thumbnail', 'thumb', 'preview', 'small', 'icon'],
  playlist: ['playlist', 'queue', 'list', 'music', 'media', 'tracklist'],

  // ─── Communication ────────────────────────────────────────────────────
  sms: ['sms', 'text', 'message', 'txt', 'text-message'],
  mms: ['mms', 'message', 'multimedia', 'picture-message'],
  voicemail: ['voicemail', 'voice', 'message', 'phone', 'call'],
  ringtone: ['ringtone', 'ring', 'tone', 'sound', 'phone', 'alert'],
  spam: ['spam', 'junk', 'unwanted', 'block', 'report'],
  unread: ['unread', 'new', 'unopened', 'fresh', 'badge'],
  read: ['read', 'opened', 'seen', 'viewed', 'checked'],

  // ─── Finance extended ─────────────────────────────────────────────────
  bitcoin: ['bitcoin', 'btc', 'crypto', 'cryptocurrency', 'blockchain', 'digital-currency'],
  ethereum: ['ethereum', 'eth', 'crypto', 'cryptocurrency'],
  blockchain: ['blockchain', 'chain', 'block', 'crypto', 'distributed', 'ledger'],
  nft: ['nft', 'token', 'digital-asset', 'crypto-art'],
  transfer: ['transfer', 'send', 'move', 'wire', 'transaction', 'remit'],
  withdraw: ['withdraw', 'take-out', 'remove', 'pull', 'cash-out'],
  deposit: ['deposit', 'put-in', 'add', 'credit', 'pay-in'],
  balance: ['balance', 'total', 'amount', 'funds', 'sum'],
  loan: ['loan', 'borrow', 'credit', 'finance', 'debt', 'mortgage'],
  mortgage: ['mortgage', 'loan', 'house', 'property', 'finance', 'home'],
  interest: ['interest', 'rate', 'apr', 'percentage', 'finance', 'growth'],

  // ─── Shopping extended ────────────────────────────────────────────────
  refund: ['refund', 'return', 'money-back', 'exchange', 'cancel'],
  exchange: ['exchange', 'swap', 'trade', 'switch', 'replace', 'barter'],
  warranty: ['warranty', 'guarantee', 'assurance', 'coverage', 'protection'],
  review: ['review', 'rating', 'stars', 'feedback', 'testimonial', 'comment'],
  wishlist: ['wishlist', 'favorites', 'saved', 'bookmarks', 'list', 'saved-items'],
  'out of stock': ['out-of-stock', 'oos', 'sold-out', 'unavailable', 'empty'],
  'in stock': ['in-stock', 'available', 'inventory', 'stock'],
  inventory: ['inventory', 'stock', 'supply', 'warehouse', 'storage'],
  warehouse: ['warehouse', 'storage', 'inventory', 'stockroom', 'depot'],

  // ─── Health extended ──────────────────────────────────────────────────
  ambulance: ['ambulance', 'emergency', 'medical', 'rescue', 'vehicle', 'paramedic'],
  pharmacy: ['pharmacy', 'drugstore', 'medicine', 'drugs', 'prescription', 'chemist'],
  prescription: ['prescription', 'rx', 'medicine', 'drug', 'doctor', 'medical'],
  stethoscope: ['stethoscope', 'doctor', 'medical', 'health', 'checkup', 'heart'],
  vaccination: ['vaccination', 'vaccine', 'shot', 'immunization', 'injection', 'medical'],
  virus: ['virus', 'germ', 'infection', 'disease', 'illness', 'covid', 'bacteria'],
  bacteria: ['bacteria', 'germ', 'microbe', 'organism', 'virus', 'infection'],
  dna: ['dna', 'genetics', 'gene', 'chromosome', 'biology', 'helix'],
  brain: ['brain', 'mind', 'intelligence', 'thinking', 'head', 'neurology'],

  // ─── Cooking / food extended ──────────────────────────────────────────
  chef: ['chef', 'cook', 'kitchen', 'culinary', 'cooking'],
  recipe: ['recipe', 'cookbook', 'ingredients', 'cooking', 'food'],
  ingredient: ['ingredient', 'component', 'food', 'recipe', 'element'],
  microwave: ['microwave', 'oven', 'cook', 'heat', 'kitchen', 'appliance'],
  oven: ['oven', 'bake', 'cook', 'roast', 'kitchen', 'appliance'],
  stove: ['stove', 'cooktop', 'burner', 'cook', 'kitchen'],
  toaster: ['toaster', 'toast', 'bread', 'kitchen', 'appliance'],
  blender: ['blender', 'mix', 'blend', 'smoothie', 'kitchen', 'appliance'],
  noodles: ['noodles', 'pasta', 'spaghetti', 'ramen', 'food', 'asian'],
  rice: ['rice', 'grain', 'food', 'asian', 'cook', 'bowl'],
  burger: ['burger', 'hamburger', 'sandwich', 'food', 'fast-food', 'beef'],
  fries: ['fries', 'chips', 'potato', 'fast-food', 'snack'],
  sushi: ['sushi', 'japanese', 'fish', 'rice', 'food', 'asian'],
  salad: ['salad', 'greens', 'vegetable', 'healthy', 'food'],
  soup: ['soup', 'broth', 'stew', 'chowder', 'food', 'warm'],
  dessert: ['dessert', 'sweet', 'cake', 'ice-cream', 'pastry', 'sugar'],

  // ─── Education extended ───────────────────────────────────────────────
  diploma: ['diploma', 'certificate', 'degree', 'graduation', 'award'],
  lecture: ['lecture', 'class', 'lesson', 'teaching', 'professor', 'academic'],
  assignment: ['assignment', 'homework', 'task', 'project', 'schoolwork'],
  exam: ['exam', 'test', 'quiz', 'assessment', 'final', 'midterm'],
  grade: ['grade', 'score', 'mark', 'result', 'gpa', 'rating'],
  scholarship: ['scholarship', 'award', 'grant', 'funding', 'education', 'merit'],
  sharpener: ['sharpener', 'sharpen', 'pencil', 'stationery', 'tool'],
  backpack: ['backpack', 'bag', 'school-bag', 'rucksack', 'bookbag'],

  // ─── Sports extended ─────────────────────────────────────────────────
  cricket: ['cricket', 'bat', 'ball', 'sport', 'wicket', 'bowling'],
  hockey: ['hockey', 'stick', 'puck', 'ice-hockey', 'field-hockey', 'sport'],
  badminton: ['badminton', 'racket', 'shuttlecock', 'birdie', 'sport'],
  tabletennis: ['tabletennis', 'ping-pong', 'paddle', 'ball', 'sport'],
  boxing: ['boxing', 'punch', 'glove', 'fight', 'sport', 'heavyweight'],
  wrestling: ['wrestling', 'wrestle', 'fight', 'mat', 'sport'],
  archery: ['archery', 'bow', 'arrow', 'target', 'shoot', 'sport'],
  fencing: ['fencing', 'sword', 'foil', 'duel', 'sport'],
  skating: ['skating', 'skate', 'ice-skate', 'roller', 'sport'],
  skiing: ['skiing', 'ski', 'snow', 'winter', 'slope', 'sport', 'mountain'],
  snowboarding: ['snowboarding', 'snowboard', 'snow', 'winter', 'sport'],
  surfing: ['surfing', 'surf', 'wave', 'ocean', 'beach', 'sport', 'board'],
  climbing: ['climbing', 'climb', 'rock', 'wall', 'mountaineer', 'sport', 'rope'],

  // ─── Misc extended ────────────────────────────────────────────────────
  broken: ['broken', 'damage', 'shattered', 'fracture', 'crack', 'error'],
  ticket: ['ticket', 'admission', 'entry', 'pass', 'voucher', 'coupon'],
  voucher: ['voucher', 'coupon', 'ticket', 'discount', 'promo', 'gift'],
  upgrade: ['upgrade', 'improve', 'enhance', 'update', 'boost', 'premium'],
  downgrade: ['downgrade', 'reduce', 'lower', 'degrade', 'worse'],
  pro: ['pro', 'professional', 'premium', 'advanced', 'plus'],
  premium: ['premium', 'pro', 'advanced', 'vip', 'exclusive'],
  free: ['free', 'gratis', 'no-cost', 'complimentary', 'zero'],
  soon: ['soon', 'coming-soon', 'upcoming', 'future', 'pending'],
  percent: ['percent', 'percentage', '%', 'proportion', 'ratio'],
  memo: ['memo', 'note', 'reminder', 'message', 'document', 'brief'],
  qrcode: ['qrcode', 'qr', 'scan', 'code', 'barcode'],
  hierarchy: ['hierarchy', 'tree', 'structure', 'org-chart', 'levels', 'nested'],
  diagram: ['diagram', 'chart', 'graph', 'schema', 'flowchart', 'visual'],
  skeleton: ['skeleton', 'bone', 'structure', 'framework', 'body'],
  bone: ['bone', 'skeleton', 'body', 'anatomy'],
  sphere: ['sphere', 'ball', 'globe', 'orb', 'round', 'circle-3d'],
  gradient: ['gradient', 'fade', 'blend', 'ombre', 'color-transition'],
  opacity: ['opacity', 'transparency', 'alpha', 'fade', 'see-through'],
  mask: ['mask', 'overlay', 'cover', 'hide', 'layer-mask'],
  setting: ['setting', 'settings', 'preference', 'option', 'config', 'setup'],

  // ─── More two-word phrases ────────────────────────────────────────────
  'new tab': ['new-tab', 'tab-add', 'plus', 'add', 'browser'],
  'new window': ['new-window', 'window-add', 'popup', 'pop-out'],
  'split screen': ['split-screen', 'split', 'side-by-side', 'dual', 'multi-window'],
  'hide password': ['eye-off', 'hide', 'invisible', 'hidden', 'private'],
  'show password': ['eye', 'show', 'visible', 'reveal', 'view'],
  'go to top': ['arrow-up', 'up', 'top', 'back-to-top', 'scroll-up'],
  'go to bottom': ['arrow-down', 'down', 'bottom', 'scroll-down'],
  'scroll to top': ['arrow-up', 'up', 'top', 'scroll-up'],
  'scroll to bottom': ['arrow-down', 'down', 'bottom', 'scroll-down'],
  'slide show': ['slideshow', 'presentation', 'deck', 'slides', 'screen'],
  'slide deck': ['slides', 'deck', 'presentation', 'slide', 'screen'],
  'weather app': ['weather', 'sun', 'rain', 'cloud', 'forecast'],
  'calendar app': ['calendar', 'date', 'schedule', 'event', 'planner'],
  'clock app': ['clock', 'time', 'alarm', 'timer', 'stopwatch'],
  'notes app': ['notes', 'note', 'memo', 'sticky', 'notepad'],
  'calculator app': ['calculator', 'calc', 'math', 'calculate'],
  'camera app': ['camera', 'photo', 'picture', 'snap', 'shutter'],
  'phone app': ['phone', 'call', 'dial', 'contact', 'mobile'],
  'messages app': ['messages', 'sms', 'chat', 'text', 'imessage'],
  'mail app': ['mail', 'email', 'inbox', 'message', 'envelope'],
  'music app': ['music', 'player', 'song', 'audio', 'itunes'],
  'photos app': ['photos', 'gallery', 'album', 'images', 'pictures'],
  'settings app': ['settings', 'gear', 'preferences', 'config', 'options'],
  'maps app': ['maps', 'map', 'navigation', 'location', 'directions'],
  'contacts app': ['contacts', 'contact', 'people', 'address-book', 'phonebook'],
  'health app': ['health', 'fitness', 'wellness', 'medical', 'activity'],
  'wallet app': ['wallet', 'money', 'payment', 'card', 'finance'],

  // ─── Common misspellings & variants ───────────────────────────────────
  recieve: ['receive', 'download', 'get', 'inbox', 'accept'],
  acheive: ['achieve', 'complete', 'success', 'goal', 'done'],
  achevement: ['achievement', 'award', 'badge', 'trophy', 'reward'],
  begining: ['beginning', 'start', 'first', 'initial', 'launch'],
  calander: ['calendar', 'date', 'schedule', 'day', 'month'],
  choise: ['choice', 'option', 'select', 'pick', 'decision'],
  collor: ['color', 'colour', 'paint', 'hue', 'shade'],
  coulour: ['color', 'colour', 'paint', 'hue', 'shade'],
  compleet: ['complete', 'done', 'finish', 'check', 'success'],
  conection: ['connection', 'connect', 'link', 'network', 'wifi'],
  conect: ['connect', 'link', 'join', 'attach', 'network'],
  configration: ['configuration', 'settings', 'setup', 'config', 'preferences'],
  controll: ['control', 'controller', 'manage', 'gamepad'],
  defaut: ['default', 'standard', 'normal', 'regular'],
  delivry: ['delivery', 'shipping', 'package', 'send'],
  destiantion: ['destination', 'location', 'place', 'target', 'goal'],
  devce: ['device', 'gadget', 'phone', 'tablet'],
  diffrent: ['different', 'distinct', 'other', 'unique'],
  disabel: ['disable', 'off', 'turn-off', 'stop'],
  documment: ['document', 'file', 'paper', 'doc', 'text'],
  downlode: ['download', 'save', 'install', 'get'],
  downloud: ['download', 'save', 'install', 'get'],
  dragge: ['drag', 'move', 'grab', 'handle'],
  dropp: ['drop', 'water', 'droplet', 'fall'],
  egnlish: ['english', 'language', 'en'],
  envlope: ['envelope', 'mail', 'email', 'letter'],
  experiance: ['experience', 'ux', 'user-experience'],
  facbook: ['facebook', 'social', 'meta'],
  favrite: ['favorite', 'favourite', 'star', 'heart', 'bookmark'],
  fileing: ['filing', 'file', 'organize', 'folder', 'archive'],
  foler: ['folder', 'directory', 'file', 'bundle'],
  foward: ['forward', 'next', 'right', 'send'],
  frequancy: ['frequency', 'hz', 'rate', 'signal'],
  friend: ['friend', 'friends', 'people', 'person', 'pal', 'buddy'],
  grafic: ['graphic', 'graphics', 'design', 'visual'],
  gurantee: ['guarantee', 'warranty', 'assurance', 'security'],
  happend: ['history', 'timeline', 'recent', 'past'],
  helth: ['health', 'medical', 'wellness', 'fitness'],
  icone: ['icon', 'symbol', 'logo', 'glyph'],
  iland: ['island', 'beach', 'tropical', 'vacation'],
  imagen: ['image', 'img', 'photo', 'picture'],
  inport: ['import', 'upload', 'bring-in', 'load'],
  instal: ['install', 'setup', 'download', 'configure'],
  insall: ['install', 'setup', 'download', 'configure'],
  integrat: ['integrate', 'integration', 'combine', 'merge'],
  invoce: ['invoice', 'bill', 'receipt', 'payment'],
  iphon: ['iphone', 'phone', 'mobile', 'apple'],
  languge: ['language', 'translate', 'locale', 'i18n'],
  librery: ['library', 'books', 'collection', 'archive'],
  licence: ['license', 'permit', 'permission', 'certificate'],
  london: ['uk', 'britain', 'great-britain'],
  loose: ['lost', 'missing', 'gone', 'disconnected'],
  mai: ['mail', 'email', 'envelope', 'message'],
  maintance: ['maintenance', 'repair', 'service', 'fix'],
  maneger: ['manager', 'boss', 'admin', 'leader'],
  messege: ['message', 'chat', 'text', 'msg', 'sms'],
  messsage: ['message', 'chat', 'text', 'msg', 'sms'],
  more: ['more', 'plus', 'additional', 'extra', 'dots'],
  mor: ['more', 'plus', 'additional', 'extra', 'dots'],
  navig: ['navigate', 'navigation', 'direction'],
  netwrok: ['network', 'internet', 'connection', 'wifi'],
  nofication: ['notification', 'alert', 'bell', 'notif'],
  noth: ['north', 'northern', 'up', 'top'],
  nothng: ['nothing', 'zero', 'empty', 'none', 'blank'],
  notificatin: ['notification', 'alert', 'bell', 'notif'],
  notificaton: ['notification', 'alert', 'bell', 'notif'],
  notifiaction: ['notification', 'alert', 'bell', 'notif'],
  obtion: ['option', 'choice', 'select', 'preference'],
  offce: ['office', 'work', 'desk', 'corporate'],
  opption: ['option', 'choice', 'select', 'preference'],
  organz: ['organize', 'arrange', 'sort', 'order'],
  pased: ['paste', 'insert', 'clipboard', 'copy'],
  passowrd: ['password', 'key', 'lock', 'secure', 'login'],
  passord: ['password', 'key', 'lock', 'secure', 'login'],
  paster: ['paste', 'insert', 'clipboard'],
  pattren: ['pattern', 'design', 'template', 'repeat'],
  phon: ['phone', 'call', 'mobile', 'telephone'],
  pictur: ['picture', 'image', 'photo', 'photo'],
  protct: ['protect', 'shield', 'secure', 'safety'],
  protrait: ['portrait', 'vertical', 'orientation', 'photo'],
  puplish: ['publish', 'share', 'post', 'release'],
  recive: ['receive', 'get', 'download', 'inbox'],
  reciver: ['receiver', 'receive', 'get', 'download'],
  refernce: ['reference', 'source', 'citation'],
  remmeber: ['remember', 'save', 'bookmark', 'pin', 'favorite'],
  requst: ['request', 'ask', 'send', 'submit'],
  restor: ['restore', 'recover', 'backup', 'revert'],
  retry: ['retry', 'retry', 'try-again', 'repeat', 'reload'],
  scedule: ['schedule', 'calendar', 'date', 'plan', 'agenda'],
  schedual: ['schedule', 'calendar', 'date', 'plan', 'agenda'],
  schecule: ['schedule', 'calendar', 'date', 'plan', 'agenda'],
  scrol: ['scroll', 'scroll', 'roll', 'slide', 'swipe'],
  searchh: ['search', 'find', 'magnifier', 'lookup'],
  secion: ['section', 'part', 'segment', 'area'],
  selectt: ['select', 'choose', 'pick', 'highlight'],
  sentting: ['setting', 'settings', 'preference', 'config', 'options'],
  sever: ['server', 'host', 'cloud', 'server'],
  shipp: ['ship', 'shipping', 'delivery', 'transport'],
  shoping: ['shopping', 'cart', 'buy', 'store', 'shop'],
  shose: ['shoes', 'sneakers', 'footwear', 'shoe'],
  singel: ['single', 'one', 'solo', 'individual'],
  slct: ['select', 'choose', 'pick', 'option'],
  slience: ['silence', 'silent', 'mute', 'quiet', 'no-sound'],
  smoth: ['smooth', 'even', 'flat', 'polished'],
  sned: ['send', 'share', 'submit', 'forward'],
  socail: ['social', 'media', 'network', 'share'],
  softwar: ['software', 'app', 'program', 'application'],
  spcae: ['space', 'cosmos', 'universe', 'astronomy'],
  speel: ['speed', 'fast', 'rapid', 'quick', 'velocity'],
  spirng: ['spring', 'season', 'nature', 'flower'],
  staion: ['station', 'stop', 'terminal', 'hub'],
  stastus: ['status', 'state', 'condition', 'mode'],
  steup: ['setup', 'configure', 'install', 'init'],
  stor: ['store', 'shop', 'market', 'buy'],
  subscri: ['subscribe', 'follow', 'join', 'register'],
  surch: ['search', 'find', 'lookup', 'scan'],
  swap: ['swap', 'switch', 'trade', 'exchange', 'replace'],
  swich: ['switch', 'toggle', 'swap', 'change'],
  synconize: ['synchronize', 'sync', 'refresh', 'update'],
  tast: ['task', 'todo', 'checklist', 'item', 'job'],
  taxt: ['text', 'type', 'font', 'write'],
  templete: ['template', 'layout', 'pattern', 'design'],
  temporay: ['temporary', 'temp', 'provisional', 'interim'],
  tet: ['text', 'type', 'font', 'write'],
  thumnail: ['thumbnail', 'thumb', 'preview', 'small'],
  toggl: ['toggle', 'switch', 'on-off', 'enable'],
  transactn: ['transaction', 'payment', 'transfer', 'purchase'],
  translt: ['translate', 'language', 'convert'],
  typeing: ['typing', 'type', 'keyboard', 'input', 'text'],
  ultil: ['utility', 'tools', 'utils', 'function'],
  unblck: ['unlock', 'unlock', 'open', 'free'],
  unddo: ['undo', 'reverse', 'revert', 'unmake'],
  uninstl: ['uninstall', 'remove', 'delete', 'wipe'],
  updaye: ['update', 'refresh', 'renew', 'upgrade'],
  upvote: ['upvote', 'up', 'like', 'thumbs-up', 'approve'],
  downvote: ['downvote', 'down', 'dislike', 'thumbs-down'],
  vald: ['valid', 'validate', 'verify', 'confirm', 'check'],
  vew: ['view', 'see', 'look', 'show', 'display'],
  visabl: ['visible', 'see', 'view', 'show', 'eye'],
  visal: ['visual', 'view', 'sight', 'vision', 'graphic'],
  volme: ['volume', 'sound', 'loud', 'speaker'],
  warrenty: ['warranty', 'guarantee', 'protection', 'assurance'],
  weght: ['weight', 'heavy', 'mass', 'scale'],
  widdth: ['width', 'wide', 'breadth', 'span'],
  writng: ['writing', 'write', 'type', 'author', 'content'],
};

function normalize(text: string): string {
  return text.toLowerCase().trim().replace(/\s+/g, ' ');
}

function tokenize(text: string): string[] {
  return normalize(text).split(' ').filter(Boolean);
}

export function isSentenceQuery(query: string): boolean {
  const trimmed = query.trim();
  if (!trimmed) return true;
  if (SENTENCE_MARKERS.test(trimmed)) return true;
  const words = tokenize(trimmed);
  // Only flag > 7 words as a sentence (was 6, which was too aggressive)
  if (words.length > 7) return true;
  // Only flag if sentence words appear AND query is 5+ words
  if (words.length >= 5 && SENTENCE_WORDS.test(trimmed)) return true;
  if (/^(how|what|where|which|why|when)\b/i.test(trimmed)) return true;
  return false;
}

function synonymBoost(query: string, name: string): number {
  const key = normalize(query);
  const list = SYNONYMS[key];
  if (!list) return 0;
  const idx = list.indexOf(name);
  if (idx === -1) return 0;
  return 3000 - idx * 100;
}

// Fuzzy partial match — how many chars of `token` appear sequentially in `str`
function fuzzyScore(str: string, token: string): number {
  let ti = 0;
  let hits = 0;
  for (const c of str) {
    if (ti < token.length && c === token[ti]) { ti++; hits++; }
  }
  return ti === token.length ? Math.round((hits / str.length) * 100) : 0;
}

function scoreIcon(icon: IconEntry, query: string, tokens: string[], weight?: IconWeight): number {
  const q = normalize(query);
  const name = icon.name;
  const nameNorm = name.replace(/-/g, ' ');
  const catNorm = icon.category.replace(/-/g, ' ').toLowerCase();
  const tagsNorm = icon.tags.map((t) => normalize(t));
  let score = 0;

  // Synonym boost
  score += synonymBoost(query, name);

  // Exact name match
  if (name === q || name === q.replace(/ /g, '-')) {
    score += 10000;
  }

  // Single token exact match
  if (tokens.length === 1 && name === tokens[0]) {
    score += 5000;
  }

  // All tokens appear in name
  if (tokens.every((t) => name.includes(t) || nameNorm.includes(t))) {
    score += 2000;
  }

  // Full tag exact match
  if (tagsNorm.some((t) => t === q)) {
    score += 1500;
  }

  for (const token of tokens) {
    // Exact tag match
    if (tagsNorm.some((t) => t === token)) score += 800;
    // Name includes token
    if (name.includes(token)) score += 600;
    // Name starts with token (prefix boost)
    if (name.startsWith(token)) score += 400;
    // Tag includes token
    if (tagsNorm.some((t) => t.includes(token))) score += 300;
    // Category match
    if (catNorm.includes(token)) score += 150;
    // Fuzzy fallback — only if no direct match
    const directMatch = name.includes(token) || tagsNorm.some((t) => t.includes(token));
    if (!directMatch) {
      const fuzz = fuzzyScore(name, token);
      if (fuzz > 70) score += Math.round(fuzz * 0.8);
    }
  }

  // Prefer shorter names (more specific)
  score += Math.max(0, 50 - name.length);

  // Weight filter
  if (weight) {
    if (icon.weights[weight]) score += 10;
    else score -= 1000;
  }

  return score;
}

export function searchIcons(
  index: IconIndex,
  query: string,
  options: { weight?: IconWeight; limit?: number } = {},
): { results: SearchResult[]; instruction: string } | { error: string } {
  if (isSentenceQuery(query)) {
    return {
      error: 'Query looks like a full sentence. Use concise keywords instead, such as "cart", "user", or "settings".',
    };
  }

  // Default limit raised from 5 → 8 for better agent context
  const limit = options.limit ?? 8;
  const tokens = tokenize(query);
  const weights: IconWeight[] = options.weight ? [options.weight] : ['outline', 'filled', 'duotone-outline', 'duotone-filled'];
  const results: SearchResult[] = [];

  for (const icon of index.icons) {
    for (const weight of weights) {
      if (!icon.weights[weight]) continue;
      const score = scoreIcon(icon, query, tokens, weight);
      if (score > 0) {
        results.push({
          name: icon.name,
          weight,
          category: icon.category,
          tags: icon.tags,
          score,
        });
      }
    }
  }

  results.sort((a, b) => b.score - a.score || a.name.length - b.name.length);

  const seen = new Set<string>();
  const deduped: SearchResult[] = [];
  for (const r of results) {
    const key = `${r.name}:${r.weight}`;
    if (seen.has(key)) continue;
    seen.add(key);
    deduped.push(r);
    if (deduped.length >= limit) break;
  }

  if (deduped.length === 0) {
    return {
      error: `No icons found for "${query}". Try a shorter or different keyword.`,
    };
  }

  return {
    results: deduped,
    instruction:
      'Pick exactly one result from the list above. Prefer the highest score. Then call view_icon to confirm the SVG, or apply_icon to generate ready-to-use code. Do not ask the user to choose.',
  };
}

export function findIcon(index: IconIndex, name: string): IconEntry | undefined {
  return index.icons.find((i) => i.name === name);
}

export function listCategories(index: IconIndex): string[] {
  return index.categories;
}
