// Auto-generated by scripts/seo/update-helmets.mjs — DO NOT EDIT
// Edit scripts/seo/config.mjs instead and re-run: node scripts/seo/update-helmets.mjs

export interface PageMeta {
  title: string;
  description: string;
  url: string;
  ogImage: string;
}

export const PAGE_META: Record<string, PageMeta> = {
  '/': { title: 'Vezham — Free Open-Source SVG Icons, Illustrations & Brand Logos', description: 'Vezham — Free open-source SVG icons, illustrations & brand logos. 3,900+ icons, 71,000+ illustrations, 4,900+ logos for React, Vue, Svelte, Flutter, Figma & more.', url: 'https://vezham.com/', ogImage: 'https://vezham.com/og/og.jpg' },
  '/icons': { title: 'Free Open-Source SVG Icons — Vezham', description: 'Browse 3,900+ free, open-source SVG icons in outline, filled, duotone-outline, and duotone-filled weights. MIT licensed.', url: 'https://vezham.com/icons', ogImage: 'https://vezham.com/og/icons.jpeg' },
  '/illustration': { title: '71,000+ Free SVG Illustrations — Open-Source Vector Graphics | Vezham', description: 'Browse 71,000+ free open-source SVG vector illustrations for React, Vue, HTML, and Figma. Download high-resolution PNG & customizable SVGs. MIT licensed.', url: 'https://vezham.com/illustration', ogImage: 'https://vezham.com/og/illustration.jpg' },
  '/logos': { title: '4,900+ Free SVG Brand Logos — High Quality Vector Logos | Vezham', description: 'Browse and download 4,900+ clean vector brand logos for tech companies, frameworks, AI, and global brands. Free SVG & PNG formats. MIT licensed.', url: 'https://vezham.com/logos', ogImage: 'https://vezham.com/og/logos.jpeg' },
  '/docs': { title: 'Vezham Docs — Get Started', description: 'Get started with Vezham. Install and use icons in React, Vue, Svelte, Flutter, Figma, VS Code, and MCP.', url: 'https://vezham.com/docs', ogImage: 'https://vezham.com/og/docs.jpg' },
  '/docs/react': { title: 'Vezham for React — Vezham', description: 'Install and use Vezham in React. Import components, customize props, tree-shake unused icons.', url: 'https://vezham.com/docs/react', ogImage: 'https://vezham.com/og/docs-react.jpg' },
  '/docs/react-native': { title: 'Vezham for React Native — Vezham', description: 'Install and use Vezham in React Native. SVG components for Expo and bare React Native.', url: 'https://vezham.com/docs/react-native', ogImage: 'https://vezham.com/og/docs-react-native.jpg' },
  '/docs/vue': { title: 'Vezham for Vue — Vezham', description: 'Install and use Vezham in Vue 3 and Nuxt 3. Import components and customize props.', url: 'https://vezham.com/docs/vue', ogImage: 'https://vezham.com/og/docs-vue.jpg' },
  '/docs/svelte': { title: 'Vezham for Svelte — Vezham', description: 'Install and use Vezham in Svelte and SvelteKit. Import components and customize props.', url: 'https://vezham.com/docs/svelte', ogImage: 'https://vezham.com/og/docs-svelte.jpg' },
  '/docs/vanilla': { title: 'Vezham for Vanilla JS — Vezham', description: 'Use Vezham icons via CDN in vanilla JavaScript and HTML. No build tools needed.', url: 'https://vezham.com/docs/vanilla', ogImage: 'https://vezham.com/og/docs-vanilla.jpg' },
  '/docs/figma': { title: 'Vezham for Figma — Vezham', description: 'Install the Vezham Figma plugin. Search, customize, and drag-and-drop icons onto your canvas.', url: 'https://vezham.com/docs/figma', ogImage: 'https://vezham.com/og/docs-figma.jpg' },
  '/docs/vscode': { title: 'Vezham for VS Code — Vezham', description: 'Install the Vezham VS Code extension. Search and insert icon code directly at your cursor.', url: 'https://vezham.com/docs/vscode', ogImage: 'https://vezham.com/og/docs-vscode.jpg' },
  '/docs/mcp': { title: 'Vezham MCP Server & CLI — Vezham', description: 'Let AI agents search 2,700+ icons, preview SVGs, and generate code. Runs as MCP server or standalone CLI.', url: 'https://vezham.com/docs/mcp', ogImage: 'https://vezham.com/og/docs-mcp.jpg' },
  '/docs/svg': { title: 'Vezham Raw SVGs — Vezham', description: 'Download and use raw Vezham SVG icons in HTML, static layouts, or CMS templates.', url: 'https://vezham.com/docs/svg', ogImage: 'https://vezham.com/og/docs.jpg' },
  '/docs/flutter': { title: 'Vezham for Flutter — Vezham', description: 'Install and use Vezham in Flutter and Dart projects. 2,700+ icons as raw SVG path strings.', url: 'https://vezham.com/docs/flutter', ogImage: 'https://vezham.com/og/docs-flutter.jpg' },
  '/packages': { title: 'Vezham Packages — Vezham', description: 'Official Vezham packages for React, React Native, Vue, Svelte, Flutter, and JavaScript.', url: 'https://vezham.com/packages', ogImage: 'https://vezham.com/og/packages.jpg' },
  '/pack': { title: 'Vezham Pack Builder — Vezham', description: 'Select and export custom icon packs. Download as SVG, PNG, or WebP ZIP files.', url: 'https://vezham.com/pack', ogImage: 'https://vezham.com/og/pack.jpg' },
  '/faq': { title: 'Vezham FAQ — Vezham', description: 'Answers about Vezham: license, framework support, Figma integration, and contributions.', url: 'https://vezham.com/faq', ogImage: 'https://vezham.com/og/faq.jpg' },
  '/support': { title: 'Support Vezham — Buy Me a Coffee', description: 'Support ongoing open-source development of Vezham. Buy us a coffee to keep 2,700+ handcrafted SVG icons free for everyone.', url: 'https://vezham.com/support', ogImage: 'https://vezham.com/og/support.jpg' },
  '/terms': { title: 'Vezham Terms of Service — Vezham', description: 'Terms of service for using the Vezham open-source icon library.', url: 'https://vezham.com/terms', ogImage: 'https://vezham.com/og/terms.jpg' },
  '/privacy': { title: 'Vezham Privacy Policy — Vezham', description: 'Privacy policy for Vezham. Learn how we handle your data.', url: 'https://vezham.com/privacy', ogImage: 'https://vezham.com/og/privacy.jpg' },
  '/license': { title: 'Vezham MIT License — Vezham', description: 'Vezham is free and open-source under the MIT license. Use in personal and commercial projects.', url: 'https://vezham.com/license', ogImage: 'https://vezham.com/og/license.jpg' },
};

/** Framework-specific docs meta (keyed by framework ID, e.g. "react", "flutter") */
export const FRAMEWORK_META: Record<string, PageMeta> = {
  'react': { title: 'Vezham for React — Vezham', description: 'Install and use Vezham in React. Import components, customize props, tree-shake unused icons.', url: 'https://vezham.com/docs/react', ogImage: 'https://vezham.com/og/docs-react.jpg' },
  'react-native': { title: 'Vezham for React Native — Vezham', description: 'Install and use Vezham in React Native. SVG components for Expo and bare React Native.', url: 'https://vezham.com/docs/react-native', ogImage: 'https://vezham.com/og/docs-react-native.jpg' },
  'vue': { title: 'Vezham for Vue — Vezham', description: 'Install and use Vezham in Vue 3 and Nuxt 3. Import components and customize props.', url: 'https://vezham.com/docs/vue', ogImage: 'https://vezham.com/og/docs-vue.jpg' },
  'svelte': { title: 'Vezham for Svelte — Vezham', description: 'Install and use Vezham in Svelte and SvelteKit. Import components and customize props.', url: 'https://vezham.com/docs/svelte', ogImage: 'https://vezham.com/og/docs-svelte.jpg' },
  'vanilla': { title: 'Vezham for Vanilla JS — Vezham', description: 'Use Vezham icons via CDN in vanilla JavaScript and HTML. No build tools needed.', url: 'https://vezham.com/docs/vanilla', ogImage: 'https://vezham.com/og/docs-vanilla.jpg' },
  'figma': { title: 'Vezham for Figma — Vezham', description: 'Install the Vezham Figma plugin. Search, customize, and drag-and-drop icons onto your canvas.', url: 'https://vezham.com/docs/figma', ogImage: 'https://vezham.com/og/docs-figma.jpg' },
  'vscode': { title: 'Vezham for VS Code — Vezham', description: 'Install the Vezham VS Code extension. Search and insert icon code directly at your cursor.', url: 'https://vezham.com/docs/vscode', ogImage: 'https://vezham.com/og/docs-vscode.jpg' },
  'mcp': { title: 'Vezham MCP Server & CLI — Vezham', description: 'Let AI agents search 2,700+ icons, preview SVGs, and generate code. Runs as MCP server or standalone CLI.', url: 'https://vezham.com/docs/mcp', ogImage: 'https://vezham.com/og/docs-mcp.jpg' },
  'svg': { title: 'Vezham Raw SVGs — Vezham', description: 'Download and use raw Vezham SVG icons in HTML, static layouts, or CMS templates.', url: 'https://vezham.com/docs/svg', ogImage: 'https://vezham.com/og/docs.jpg' },
  'flutter': { title: 'Vezham for Flutter — Vezham', description: 'Install and use Vezham in Flutter and Dart projects. 2,700+ icons as raw SVG path strings.', url: 'https://vezham.com/docs/flutter', ogImage: 'https://vezham.com/og/docs-flutter.jpg' },
};
